use super::sink::println;

pub(super) fn print() {
    println!("  edit fill-fields <파일.hwp|파일.hwpx> --data <JSON|@파일> [-o <출력>] [옵션]");
    println!("      누름틀에 값을 채운다 (서식 자동 작성/메일머지)");
    println!();
    println!("      --data <JSON|@파일>       {{\"필드이름\":\"값\"}} 형식. @경로면 파일에서 읽음");
    println!(
        "      -o, --output <파일>       출력 파일 (기본: 입력명_filled.<입력과 같은 확장자>)"
    );
    println!("      --dry-run                 파일을 쓰지 않고 변경 예정 내역만 보고");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!();
    println!("  edit replace-text <파일.hwp|파일.hwpx> --find <문자열> --replace <문자열> [옵션]");
    println!("      문서 전체 일괄 치환 (기관명 변경·연도 갱신·용어 정비). 본문+표 셀");
    println!();
    println!("      --find <문자열>           찾을 문자열 (빈 문자열 불가)");
    println!("      --replace <문자열>        바꿀 문자열 (\"\" 이면 삭제)");
    println!("      --ignore-case             대소문자 무시");
    println!(
        "      -o, --output <파일>       출력 파일 (기본: 입력명_replaced.<입력과 같은 확장자>)"
    );
    println!("      --dry-run                 파일을 쓰지 않고 치환 예정 건수만 보고");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!("      치환 0건이면 출력 파일을 만들지 않음");
    println!();
    println!("  edit set-cell <파일> --table <번호> --row <행> --col <열> --text <문자열> [옵션]");
    println!("      표 격자 좌표로 셀 값을 바꾼다 (실물 표 양식 채우기)");
    println!();
    println!("      --table/--row/--col       export-tables 격자와 같은 좌표 (0부터)");
    println!("      --text <문자열>           셀에 넣을 값 (비우기는 \"\", 줄바꿈·탭 불가)");
    println!("      --keep-style              셀 안내문 스타일 상속(기본: 검정 글씨로 기록)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_cell.<입력과 같은 확장자>)");
    println!("      --dry-run                 파일을 쓰지 않고 old→new 만 보고");
    println!("      (값이 칸 폭을 넘치면 --json 응답의 overflow 로 알린다 — 채우기는 막지 않음)");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!("      병합으로 덮인 칸은 앵커 좌표 안내와 함께 오류 종료");
    println!();
    println!("  edit insert-text-in-cell <파일> --table N --row N --col N --text <문자열> [옵션]");
    println!("      표 셀 문단의 문자 오프셋에 텍스트를 끼운다 (칸 전체를 덮지 않음)");
    println!();
    println!("      --table/--row/--col       export-tables 격자와 같은 좌표 (0부터)");
    println!("      --text <문자열>           끼울 문자열 (빈 문자열 불가)");
    println!("      --offset N                셀 문단 문자 오프셋 (0부터, 기본 0)");
    println!("      --cell-para N             셀 안 문단 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_cellins.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-text-in-cell <파일> --table N --row N --col N --count N [옵션]");
    println!("      표 셀 문단의 문자 오프셋에서 글자를 지운다");
    println!();
    println!("      --table/--row/--col       export-tables 격자와 같은 좌표 (0부터)");
    println!("      --count N                 지울 글자 수 (1 이상)");
    println!("      --offset N                셀 문단 문자 오프셋 (0부터, 기본 0)");
    println!("      --cell-para N             셀 안 문단 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_celldel.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit set-page-def <파일> --props <JSON> [옵션]");
    println!("      구역의 용지 설정(너비·높이·여백)을 바꾼다");
    println!();
    println!("      --props <JSON>            HWPUNIT 용지 설정(JSON, 필수)");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_pagedef.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit set-section-def <파일> --props <JSON> [옵션]");
    println!("      구역 정의(머리말 감추기·시작 번호 등)를 바꾼다");
    println!();
    println!("      --props <JSON>            구역 정의 JSON (필수)");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_secdef.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!(
        "  edit insert-text <파일> --text <문자열> [--section N] [--para N] [--offset N] [옵션]"
    );
    println!("      문단 좌표에 새 텍스트를 삽입한다 (없는 자리에 글자를 넣는 축)");
    println!();
    println!("      --text <문자열>           넣을 문자열 (빈 문자열 불가)");
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      --offset 가 문단 길이와 같으면 끝에 붙인다. 넘으면 인자 오류");
    println!(
        "      -o, --output <파일>       출력 파일 (기본: 입력명_inserted.<입력과 같은 확장자>)"
    );
    println!("      --dry-run                 파일을 쓰지 않고 삽입 예정만 보고");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!();
    println!("  edit delete-text <파일> --count N [--section N] [--para N] [--offset N] [옵션]");
    println!("      문단 좌표에서 글자를 지운다");
    println!();
    println!("      --count N                 지울 글자 수 (1 이상)");
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_deltext.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-paragraph <파일> [--section N] [--para N] [옵션]");
    println!("      빈 문단을 끼운다 (앞 문단 서식 상속, 한글 Enter)");
    println!();
    println!("      --section/--para          구역·끼울 문단 번호 (0부터, 기본 0)");
    println!(
        "      -o, --output <파일>       출력 파일 (기본: 입력명_paragraph.<입력과 같은 확장자>)"
    );
    println!("      --dry-run                 파일을 쓰지 않고 삽입 예정만 보고");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!();
    println!("  edit delete-paragraph <파일> [--section N] [--para N] [옵션]");
    println!("      지정 문단을 지운다 (구역 마지막 문단은 거부)");
    println!();
    println!("      --section/--para          구역·지울 문단 번호 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_delpara.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit merge-paragraph <파일> [--section N] [--para N] [옵션]");
    println!("      지정 문단을 바로 앞 문단에 합친다 (para 0 은 거부)");
    println!();
    println!("      --section/--para          구역·합칠 문단 번호 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_mergepara.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-page-break <파일> [--section N] [--para N] [--offset N] [옵션]");
    println!("      문단을 가르고 쪽 나눔을 넣는다");
    println!();
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_pagebreak.<확장자>)");
    println!("      --dry-run                 파일을 쓰지 않고 예정만 보고");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!();
    println!("  edit insert-column-break <파일> [--section N] [--para N] [--offset N] [옵션]");
    println!("      문단을 가르고 단 나눔을 넣는다");
    println!();
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_colbreak.<확장자>)");
    println!("      --dry-run                 파일을 쓰지 않고 예정만 보고");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!();
    println!("  edit insert-table <파일> --rows N --cols N [옵션]");
    println!("      본문 좌표에 빈 표를 만든다");
    println!();
    println!("      --rows/--cols             행·열 수 (1 이상, 열은 256 이하)");
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_table.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit set-numbering-restart <파일> --mode N [옵션]");
    println!("      문단 번호 매기기를 다시 시작한다");
    println!();
    println!("      --mode N                  0=해제, 1=이전 이어, 2=새 시작");
    println!("      --count N                 mode=2 일 때 시작 번호 (기본 1)");
    println!("      --section/--para          구역·문단 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_numrst.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-row <파일> --table <번호> --row <행> [--below] [옵션]");
    println!("      본문 최상위 표에 행을 끼운다 (export-tables 좌표)");
    println!();
    println!("      --table/--row             표 번호·기준 행 (0부터)");
    println!("      --below                   지정 행 아래(생략 시 위)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_row.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-col <파일> --table <번호> --col <열> [--right] [옵션]");
    println!("      본문 최상위 표에 열을 끼운다 (export-tables 좌표)");
    println!();
    println!("      --table/--col             표 번호·기준 열 (0부터)");
    println!("      --right                   지정 열 오른쪽(생략 시 왼쪽)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_col.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-row <파일> --table <번호> --row <행> [옵션]");
    println!("      본문 최상위 표에서 행을 지운다 (export-tables 좌표)");
    println!();
    println!("      --table/--row             표 번호·지울 행 (0부터)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_delrow.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-col <파일> --table <번호> --col <열> [옵션]");
    println!("      본문 최상위 표에서 열을 지운다 (export-tables 좌표)");
    println!();
    println!("      --table/--col             표 번호·지울 열 (0부터)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_delcol.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit merge-cells <파일> --table <번호> --row <행> --col <열> --end-row <행> --end-col <열> [옵션]");
    println!("      본문 최상위 표의 셀 사각형을 병합한다");
    println!();
    println!("      --table/--row/--col       시작 표·행·열 (0부터)");
    println!("      --end-row/--end-col       끝 행·열 (포함)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_merge.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit split-cell <파일> --table <번호> --row <행> --col <열> [옵션]");
    println!("      본문 최상위 표의 병합 셀을 다시 나눈다");
    println!();
    println!("      --table/--row/--col       표·행·열 (0부터)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_split.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit split-cell-into <파일> --table N --row N --col N --rows N --cols N [옵션]");
    println!("      본문 최상위 표의 셀을 n행 × m열로 나눈다");
    println!();
    println!("      --table/--row/--col       표·행·열 (0부터)");
    println!("      --rows/--cols             나눌 행·열 수 (1 이상)");
    println!("      --equal-row-height        나눈 행 높이를 같게");
    println!("      --merge-first             병합 셀이면 먼저 해제");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_splitinto.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit split-table <파일> --table N --row N [옵션]");
    println!("      본문 최상위 표를 지정 행에서 둘로 나눈다");
    println!();
    println!("      --table N                 export-tables 의 최상위 표 번호 (0부터)");
    println!("      --row N                   뒤 표가 시작되는 행 (1 이상, 첫 행 거부)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_tblsplit.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit fit-table <파일> --table N [옵션]");
    println!("      본문 최상위 표를 페이지 본문 폭에 맞춰 비례 축소한다");
    println!();
    println!("      --table N                 export-tables 의 최상위 표 번호 (0부터)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_fittbl.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit resize-table <파일> --table N --row N --col N [옵션]");
    println!("      본문 최상위 표의 행/열 크기를 한 걸음(283 HWPUNIT) 조절한다");
    println!();
    println!("      --table/--row/--col       표·행·열 (0부터)");
    println!("      --vertical                행 높이 (생략 시 열 폭)");
    println!("      --forward                 늘리기 (생략 시 줄이기)");
    println!("      --line                    경계만 옮김 (이웃과 짝)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_tblrsz.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit merge-table <파일> --table N [옵션]");
    println!("      본문 최상위 표에 바로 다음 표를 이어 붙인다");
    println!();
    println!("      --table N                 export-tables 의 최상위 표 번호 (0부터)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_mergetbl.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit set-column-widths <파일> --table N --widths W1,W2,... [옵션]");
    println!("      본문 최상위 표의 열 폭을 HWPUNIT 절대값으로 설정한다");
    println!();
    println!("      --table N                 export-tables 의 최상위 표 번호 (0부터)");
    println!("      --widths W1,W2,...        열 폭 (개수는 열 수와 같아야 함, 1 이상)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_colw.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit move-table <파일> --table N --dx N --dy N [옵션]");
    println!("      본문 최상위 표의 위치 오프셋을 옮긴다");
    println!();
    println!("      --table N                 export-tables 의 최상위 표 번호 (0부터)");
    println!("      --dx/--dy                 가로·세로 이동량 (HWPUNIT, 음수 허용)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_movetbl.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit set-cell-props <파일> --table N --row N --col N --props <JSON> [옵션]");
    println!("      본문 최상위 표 셀 속성(세로정렬·여백·폭 등)을 고친다");
    println!();
    println!("  edit set-table-props <파일> --table N --props <JSON> [옵션]");
    println!("      본문 최상위 표 속성(칸간격·여백·글자처럼·배치 등)을 고친다");
    println!();
    println!("      --table/--row/--col       표·행·열 (0부터, export-tables index)");
    println!("      --props <JSON>            셀 속성 (예: {{\"verticalAlign\":1}})");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_cellprop.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-footnote <파일> [--section N] [--para N] [--offset N] [옵션]");
    println!("      문단 좌표에 각주를 끼운다");
    println!();
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_footnote.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-endnote <파일> [--section N] [--para N] [--offset N] [옵션]");
    println!("      문단 좌표에 미주를 끼운다");
    println!();
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_endnote.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-equation <파일> --script <수식> [옵션]");
    println!("      본문 문단 좌표에 수식을 끼운다 (표 셀/글상자 내부는 미지원)");
    println!();
    println!("      --script <수식>           한컴 수식 스크립트 (빈 문자열 불가)");
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      --font-size N             글자 크기 (HWPUNIT, 기본 1000)");
    println!("      --color N                 RGB 정수 (기본 0=검정)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_eq.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-footnote <파일> --section N --para N --ctrl N [옵션]");
    println!("      본문 각주/미주 컨트롤을 지운다");
    println!();
    println!("      --section/--para/--ctrl   구역·문단·컨트롤 인덱스 (0부터, 필수)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_delfn.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-equation <파일> --section N --para N --ctrl N [옵션]");
    println!("      본문 수식 컨트롤을 지운다");
    println!();
    println!("      --section/--para/--ctrl   구역·문단·컨트롤 인덱스 (0부터, 필수)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_deleq.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!(
        "  edit add-bookmark <파일> --name <이름> [--section N] [--para N] [--offset N] [옵션]"
    );
    println!("      지정 좌표에 책갈피를 넣는다 (같은 이름은 거부)");
    println!();
    println!("      --name <이름>             책갈피 이름 (필수)");
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_bookmark.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-bookmark <파일> --section N --para N --ctrl N [옵션]");
    println!("      책갈피 컨트롤을 지운다");
    println!();
    println!("      --section/--para/--ctrl   구역·문단·컨트롤 인덱스 (0부터, 필수)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_delbm.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit rename-bookmark <파일> --section N --para N --ctrl N --name <이름> [옵션]");
    println!("      책갈피 이름을 바꾼다 (같은 이름은 거부)");
    println!();
    println!("      --section/--para/--ctrl   구역·문단·컨트롤 인덱스 (0부터, 필수)");
    println!("      --name <이름>             새 책갈피 이름 (필수)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_renbm.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-header-footer <파일> --header|--footer [옵션]");
    println!("      머리말/꼬리말 컨트롤을 지운다");
    println!();
    println!("      --header / --footer       둘 중 하나 필수");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      --apply-to N              0 양쪽 / 1 짝수 / 2 홀수 (기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_delhf.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-table <파일> --table <번호> [옵션]");
    println!("      본문 최상위 표를 지운다 (export-tables 좌표)");
    println!();
    println!("      --table                   표 번호 (0부터)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_deltable.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-header-footer-text <파일> --header|--footer --text <문자열> [옵션]");
    println!("      기존 머리말/꼬리말 문단에 텍스트를 끼운다");
    println!();
    println!("      --header / --footer       둘 중 하나 필수");
    println!("      --text <문자열>           넣을 문자열 (필수, 빈 문자열 불가)");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      --apply-to N              0 양쪽 / 1 짝수 / 2 홀수 (기본 0)");
    println!("      --para N                  머리말/꼬리말 안 문단 (0부터, 기본 0)");
    println!("      --offset N                문단 안 문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_hfins.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit set-header-footer-text <파일> --header|--footer --text <문자열> [옵션]");
    println!("      기존 머리말/꼬리말 문단 텍스트를 통째로 바꾼다");
    println!();
    println!("      --header / --footer       둘 중 하나 필수");
    println!("      --text <문자열>           바꿀 문자열 (필수, 빈 문자열 불가)");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      --apply-to N              0 양쪽 / 1 짝수 / 2 홀수 (기본 0)");
    println!("      --para N                  머리말/꼬리말 안 문단 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_hfset.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-hf-text <파일> --header|--footer --count <글자수> [옵션]");
    println!("      기존 머리말/꼬리말 문단에서 글자를 지운다");
    println!();
    println!("      --header / --footer       둘 중 하나 필수");
    println!("      --count <글자수>          지울 글자 수 (필수, 1 이상)");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      --apply-to N              0 양쪽 / 1 짝수 / 2 홀수 (기본 0)");
    println!("      --para N                  머리말/꼬리말 안 문단 (0부터, 기본 0)");
    println!("      --offset N                문단 안 문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_hfdeltxt.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit split-paragraph-in-hf <파일> --header|--footer [옵션]");
    println!("      기존 머리말/꼬리말 문단을 오프셋에서 나눈다");
    println!();
    println!("      --header / --footer       둘 중 하나 필수");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      --apply-to N              0 양쪽 / 1 짝수 / 2 홀수 (기본 0)");
    println!("      --para N                  머리말/꼬리말 안 문단 (0부터, 기본 0)");
    println!("      --offset N                문단 안 문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_hfsplit.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit merge-paragraph-in-hf <파일> --header|--footer [옵션]");
    println!("      머리말/꼬리말 문단을 바로 앞 문단과 합친다");
    println!();
    println!("      --header / --footer       둘 중 하나 필수");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      --apply-to N              0 양쪽 / 1 짝수 / 2 홀수 (기본 0)");
    println!("      --para N                  합쳐질 문단 (1부터, 기본 1)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_hfmerge.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit split-paragraph-in-cell <파일> --table N --row N --col N [옵션]");
    println!("      표 셀 문단을 오프셋에서 나눈다");
    println!();
    println!("      --table/--row/--col       export-tables 격자와 같은 좌표 (0부터)");
    println!("      --cell-para N             셀 안 문단 (0부터, 기본 0)");
    println!("      --offset N                문단 안 문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_cellsplit.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit merge-paragraph-in-cell <파일> --table N --row N --col N [옵션]");
    println!("      표 셀 문단을 바로 앞 문단과 합친다");
    println!();
    println!("      --table/--row/--col       export-tables 격자와 같은 좌표 (0부터)");
    println!("      --cell-para N             합쳐질 셀 문단 (1부터, 기본 1)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_cellmerge.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit apply-char-format <파일> --props <JSON> [옵션]");
    println!("      본문 문단 글자 범위에 글자 서식을 적용한다");
    println!();
    println!("      --props <JSON>            글자 서식 (예: {{\"bold\":true}})");
    println!("      --section/--para          구역·문단 인덱스 (0부터, 기본 0)");
    println!("      --offset N                시작 문자 오프셋 (0부터, 기본 0)");
    println!("      --count N                 적용 글자 수 (생략 시 문단 끝까지)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_chfmt.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit apply-para-format <파일> --props <JSON> [옵션]");
    println!("      본문 문단에 문단 서식을 적용한다");
    println!();
    println!("      --props <JSON>            문단 서식 (예: {{\"alignment\":\"center\"}})");
    println!("      --section/--para          구역·문단 인덱스 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_pfmt.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit apply-style <파일> --style N [옵션]");
    println!("      본문 문단에 스타일을 적용한다");
    println!();
    println!("      --style N                 docInfo 스타일 인덱스 (0부터, 필수)");
    println!("      --section/--para          구역·문단 인덱스 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_style.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit apply-cell-style <파일> --table N --row N --col N --style N [옵션]");
    println!("      표 셀 문단에 스타일을 적용한다");
    println!();
    println!("      --table/--row/--col       export-tables 격자와 같은 좌표 (0부터)");
    println!("      --style N                 docInfo 스타일 인덱스 (0부터, 필수)");
    println!("      --cell-para N             셀 안 문단 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_cellstyle.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!(
        "  edit apply-para-format-in-cell <파일> --table N --row N --col N --props <JSON> [옵션]"
    );
    println!("      표 셀 문단에 문단 서식을 적용한다");
    println!();
    println!("      --table/--row/--col       export-tables 격자와 같은 좌표 (0부터)");
    println!("      --props <JSON>            문단 서식 (예: {{\"alignment\":\"center\"}})");
    println!("      --cell-para N             셀 안 문단 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_cellpfmt.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-control <파일> --section N --para N --ctrl N [옵션]");
    println!("      문단이 담은 컨트롤 하나를 지운다 (갈래 무관)");
    println!();
    println!("  edit insert-header-footer <파일> --header|--footer [옵션]");
    println!("      머리말 또는 꼬리말을 만든다 (같은 apply-to 가 있으면 거부)");
    println!();
    println!("      --header / --footer       둘 중 하나 필수");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      --apply-to N              0 양쪽 / 1 짝수 / 2 홀수 (기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_hf.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-field-in-hf <파일> --header|--footer --field-type N [옵션]");
    println!("      기존 머리말/꼬리말 문단에 필드 마커를 넣는다");
    println!();
    println!("      --header / --footer       둘 중 하나 필수");
    println!("      --field-type N            1 쪽번호 / 2 총쪽수 / 3 파일이름");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      --apply-to N              0 양쪽 / 1 짝수 / 2 홀수 (기본 0)");
    println!("      --para N                  머리말/꼬리말 안 문단 (0부터, 기본 0)");
    println!("      --offset N                문단 안 문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_hffield.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit set-column-def <파일> --count N [옵션]");
    println!("      구역의 단(다단) 정의를 바꾼다");
    println!();
    println!("      --count N                 단 수 (1 이상, 필수)");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      --type N                  0 일반 / 1 배분 / 2 평행 (기본 0)");
    println!("      --same-width              단 너비 동일 (기본)");
    println!("      --mixed-width             단 너비를 따로 둔다");
    println!("      --spacing N               단 간격 (HWPUNIT, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_coldef.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit split-paragraph <파일> [--section N] [--para N] [--offset N] [옵션]");
    println!("      본문 문단을 지정 오프셋에서 가른다");
    println!();
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_splitpara.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit set-page-hide <파일> [옵션]");
    println!("      문단에 쪽 감추기(PageHide) 컨트롤을 넣거나 갱신한다");
    println!();
    println!("      --section/--para          구역·문단 (0부터, 기본 0)");
    println!("      --hide-header             머리말 감추기");
    println!("      --hide-footer             꼬리말 감추기");
    println!("      --hide-master             바탕쪽 감추기");
    println!("      --hide-border             테두리 감추기");
    println!("      --hide-fill               배경 감추기");
    println!("      --hide-page-num           쪽번호 감추기");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_pagehide.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit transpose-table <파일> --table <번호> [옵션]");
    println!("      본문 최상위 표의 행/열을 제자리에서 바꾼다 (병합 셀 거부)");
    println!();
    println!("      --table <번호>            export-tables 의 본문 최상위 표 번호");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_transpose.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!(
        "  edit set-equation-properties <파일> --section N --para N --ctrl N --props <JSON> [옵션]"
    );
    println!("      본문 수식 컨트롤의 속성을 JSON으로 변경한다");
    println!();
    println!("      --section/--para/--ctrl   구역·문단·컨트롤 인덱스 (0부터, 필수)");
    println!("      --props <JSON>            수식 속성 JSON 객체 (필수)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_eqprop.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit insert-image <파일> --image <그림> [옵션]");
    println!("      도장·서명 그림을 쪽 좌표에 붙인다 (용지 기준 떠 있는 그림)");
    println!();
    println!("      --image <경로>            png·jpg·jpeg·bmp·tif·tiff (그 밖은 인자 오류)");
    println!("      --page <번호>             붙일 쪽 (0부터, 기본 0)");
    println!("      --x/--y <값>              용지 왼쪽 위 모서리 기준 위치 (기본 0)");
    println!("      --width/--height <값>     그림 크기 (생략: 원본 픽셀 ×75, 한쪽만: 비율 유지)");
    println!(
        "      길이 단위는 모두 **HWPUNIT(1/7200 inch)** — 픽셀이 아니다 (A4 세로 59528×84188)"
    );
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_image.<입력과 같은 확장자>)");
    println!("      --dry-run                 파일을 쓰지 않고 배치 예정만 보고");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!("      (쪽 밖으로 나가면 자르지 않고 --json 응답의 overflow 로 알린다)");
    println!();
    println!("  edit insert-picture <파일> --image <그림> [옵션]");
    println!("      문단 좌표에 본문 그림을 끼운다 (insert-image 도장·서명과 다름)");
    println!();
    println!("      --image <경로>            png·jpg·jpeg·bmp·tif·tiff (그 밖은 인자 오류)");
    println!("      --section/--para/--offset 구역·문단·문자 오프셋 (0부터, 기본 0)");
    println!("      --x/--y <값>              용지 기준 위치 HWPUNIT (기본 0)");
    println!("      --width/--height <값>     그림 크기 (생략: 원본 픽셀 ×75, 한쪽만: 비율 유지)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_picture.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-picture <파일> --section N --para N --ctrl N [옵션]");
    println!("      본문 그림 컨트롤을 지운다");
    println!();
    println!("      --section/--para/--ctrl   구역·문단·컨트롤 인덱스 (0부터, 필수)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_delpic.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit delete-shape <파일> --section N --para N --ctrl N [옵션]");
    println!("      본문 도형 컨트롤을 지운다");
    println!();
    println!("      --section/--para/--ctrl   구역·문단·컨트롤 인덱스 (0부터, 필수)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_delshape.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("  edit ungroup-shape <파일> --section N --para N --ctrl N [옵션]");
    println!("      본문 묶음 도형을 풀어 자식 개체를 되돌린다");
    println!();
    println!("      --section/--para/--ctrl   구역·문단·컨트롤 인덱스 (0부터, 필수)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_ungroup.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!("      edit 명령 공통: 산출물은 **입력 형식을 보존**한다 (HWPX 입력 → HWPX 산출).");
    println!("  edit group-shapes <파일> --targets P,C;P,C [옵션]");
    println!("      같은 구역의 도형/그림을 하나로 묶는다");
    println!();
    println!("      --targets P,C;P,C         문단·컨트롤 좌표 2개 이상 (0부터)");
    println!("      --section N               구역 (0부터, 기본 0)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_grpshape.<확장자>)");
    println!("      --dry-run/--json          형제 edit 과 같음");
    println!();
    println!(
        "  edit redact <파일.hwp|파일.hwpx> [--kind …] [--dry-run] [--no-raw] [-o <출력>|--in-place]"
    );
    println!("      공개 전 개인정보 마스킹 — 주민등록번호·전화·이메일·카드번호");
    println!();
    println!("      --kind <목록>             ssn|phone|email|card|all (쉼표 구분, 기본 all)");
    println!("      --mask <문자>             마스킹 문자 한 글자 (기본 *, 자릿수 보존)");
    println!("      --dry-run                 **권장 첫 단계** — 무엇이 지워질지만 보고");
    println!("      --no-raw                  findings[].raw(원문 개인정보)를 봉투에서 뺀다");
    println!("      -o, --output <파일>       출력 파일");
    println!("      --in-place                원본을 덮어쓴다 (되돌릴 수 없음)");
    println!("      --verify                  저장 직후 IR 자기검증 (차이 시 exit 3)");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!("      되돌릴 수 없는 작업이다 — 먼저 원본을 복사해 두고, --dry-run 으로 확인하라.");
    println!("      -o 도 --in-place 도 없으면 원본 보호를 위해 실행을 거부한다 (exit 2).");
    println!("      탐지는 보수적이다: 주민등록번호는 검증 숫자, 카드는 Luhn 을 통과해야 하고");
    println!(
        "      전화는 하이픈이 있는 이동전화·서울(02) 번호만 본다 (오탐이 본문을 훼손하므로)."
    );
    println!("      --dry-run 출력에는 원문 개인정보가 그대로 들어간다 — 로그에 남기지 말 것.");
    println!("      로그·이슈에 봉투를 그대로 붙여야 한다면 --no-raw 를 함께 써서 raw 를 빼라.");
    println!();
    println!("  edit sanitize <파일.hwp|파일.hwpx> [--keep-preview] [-o <출력>] [--json]");
    println!("      문서 메타데이터 제거 — 작성자·제목·최종수정자·작성일·미리보기");
    println!();
    println!("      --keep-preview            미리보기 이미지를 남긴다 (기본: 제거)");
    println!("      -o, --output <파일>       출력 파일 (기본: 입력명_sanitized.<입력 확장자>)");
    println!("      --json                    계약 봉투 JSON을 stdout에 출력");
    println!("      본문 내용은 건드리지 않는다. 지운 항목은 removed[] 로 보고한다.");
    println!();
    println!("      edit 명령 공통: 산출물은 **입력 형식을 보존**한다 (HWPX 입력 → HWPX 산출).");
    println!("      HWPX 입력에 -o ….hwp 를 지정하면 그 경로를 존중해 HWP5 로 저장하되");
    println!("      형식 변경(이미지·차트 유실 가능)을 stderr 로 경고한다.");
    println!();
}
