#!/usr/bin/env python3
"""Korean public-document replay/audit/lineage fixture catalog.

Each row is a distinct contract axis (plan action, document family,
exception needle, or chronicle break). Indices alone are not a case.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

SAMPLE_HWP = "samples/basic/issue2007_nested_cell_pagination_42065.hwp"
SAMPLE_HWPX = "samples/exam_kor.hwpx"
SAMPLE_FORM = "samples/basic/blank2010.hwp"
SAMPLE_TABLE = "samples/basic/calendar_year.hwp"


@dataclass(frozen=True)
class Scenario:
    ident: str
    family: str
    genre: str
    title: str
    why: str
    input_path: str
    output_name: str
    steps: list[dict[str, Any]]
    notes: str
    related: tuple[str, ...] = ("#4391", "#5478")
    ext: str = "hwp"


@dataclass(frozen=True)
class ExceptionSpec:
    ident: str
    command: str
    argv: list[str]
    exit: int
    stdout_bytes: int
    needle: str
    envelope_keys: tuple[str, ...]
    why: str
    family: str


@dataclass(frozen=True)
class AuditLayout:
    ident: str
    title: str
    why: str
    members: tuple[str, ...]
    ignored: tuple[str, ...]
    total: int
    reproduced: int
    failed_kinds: tuple[str, ...]
    exit: int
    notes: str


@dataclass(frozen=True)
class LineageTopo:
    ident: str
    title: str
    why: str
    depth: int
    valid: bool
    broken_axis: str | None
    deep: bool
    exit: int
    links: tuple[dict[str, Any], ...]
    notes: str


def replace_text(find: str, replace: str, **extra: Any) -> dict[str, Any]:
    step = {"action": "replace_text", "find": find, "replace": replace}
    step.update(extra)
    return step


def fill_fields(data: dict[str, Any]) -> dict[str, Any]:
    return {"action": "fill_fields", "data": data}


def set_cell(table: int, row: int, col: int, text: str) -> dict[str, Any]:
    return {
        "action": "set_cell",
        "table": table,
        "row": row,
        "col": col,
        "text": text,
    }


def set_checkbox(name: str, checked: bool) -> dict[str, Any]:
    return {"action": "set_checkbox", "name": name, "checked": checked}


def _scenarios() -> list[Scenario]:
    s = SAMPLE_HWP
    x = SAMPLE_HWPX
    f = SAMPLE_FORM
    t = SAMPLE_TABLE
    return [
        Scenario(
            "notice_year",
            "공문",
            "연도갱신",
            "시행문 본문 연도 2025→2026",
            "연말 공문은 문서번호 체계를 유지한 채 본문 연도만 바꾼다. "
            "1-step replace_text 는 영수증 steps=1 과 1:1 이다.",
            s,
            "notice-2026.hwp",
            [replace_text("2025", "2026")],
            "contract tests 결정론 표본과 같은 1-step 형태",
        ),
        Scenario(
            "org_rename",
            "공문",
            "기관개칭",
            "안전행정부→행정안전부 전건 치환",
            "정부조직 개칭은 본문·직인 캡션·수신처에 동시에 남는다. "
            "occurrence 생략 = 전건. 영수증은 치환 횟수가 아니라 step 수다.",
            s,
            "org-rename.hwp",
            [replace_text("안전행정부", "행정안전부")],
            "find≠replace — 산출 해시가 입력과 달라질 수 있다",
        ),
        Scenario(
            "dept_rename",
            "공문",
            "부서개칭",
            "총무과→운영지원과",
            "과 단위 직제 개편은 발신 명의만 바꾼다. 기관 전체 개칭과 "
            "구분하려고 별 케이스로 둔다.",
            s,
            "dept-rename.hwp",
            [replace_text("총무과", "운영지원과")],
            "같은 문서 가족, 다른 find 축",
        ),
        Scenario(
            "addr_fix",
            "공문",
            "주소정정",
            "세종 도움5로→도움6로",
            "이전 고시의 도로명 오기는 제3자 재현 때 같은 산출이어야 한다. "
            "주소 한 줄만 바꾸는 계획이 영수증 한 장이다.",
            s,
            "addr-fix.hwp",
            [replace_text("도움5로", "도움6로")],
            "한글 도로명 — NFC 원문 가정",
        ),
        Scenario(
            "phone_hyphen",
            "공문",
            "전화형식",
            "0210002114→02-2100-2114",
            "민원 안내 전화번호 하이픈 정규화. 숫자만 바뀌지 않고 "
            "구분자가 생기므로 바이트가 길어진다.",
            s,
            "phone-hyphen.hwp",
            [replace_text("0210002114", "02-2100-2114")],
            "출력 바이트 길이 변화는 해시 계약에 영향 없음",
        ),
        Scenario(
            "amount_comma",
            "예산",
            "금액표기",
            "1000000원→1,000,000원",
            "예산서 천 단위 콤마. 숫자 값은 같고 표기만 바뀐다. "
            "영수증은 표기 바이트를 해시한 것이지 수치 동일성을 말하지 않는다.",
            t,
            "amount-comma.hwp",
            [replace_text("1000000원", "1,000,000원")],
            "표 문서 샘플",
        ),
        Scenario(
            "deadline_iso",
            "고시",
            "마감일",
            "제출기한 2026.3.31.→2026-03-31",
            "점 구분 일자를 ISO 로 정규화한다. 날짜 의미는 같고 바이트는 다르다.",
            s,
            "deadline-iso.hwp",
            [replace_text("2026.3.31.", "2026-03-31")],
            "고시 본문 일자 축",
        ),
        Scenario(
            "law_ref",
            "법령",
            "조문인용",
            "국가공무원법 제69조→제68조",
            "잘못된 조문 인용을 고친다. 한 글자 차이가 산출 해시를 바꾼다.",
            s,
            "law-ref.hwp",
            [replace_text("국가공무원법 제69조", "국가공무원법 제68조")],
            "조문 번호는 데이터이지 서명이 아니다",
        ),
        Scenario(
            "page_ref",
            "공문",
            "쪽참조",
            "붙임 2쪽→붙임 3쪽",
            "첨부 쪽수 정정. 쪽 참조는 렌더 쪽수와 무관한 본문 문자열이다.",
            s,
            "page-ref.hwp",
            [replace_text("붙임 2쪽", "붙임 3쪽")],
            "page-count 석과 무관 — 본문 치환만",
        ),
        Scenario(
            "footer_page",
            "공문",
            "바닥글",
            "바닥글 쪽 표기 - 1 - 유지",
            "바닥글 장식을 같은 문자열로 치환한다. find==replace 는 "
            "replay_contract 의 결정론 표본(산출=입력 가능)이다.",
            s,
            "footer-keep.hwp",
            [replace_text("- 1 -", "- 1 -")],
            "idempotent step — 입력 스니펫이 문서에 있어야 엔진이 산다",
        ),
        Scenario(
            "title_typo",
            "공문",
            "오탈",
            "제목 시정→시장",
            "한글 오탈 한 글자. 제3자 verify 가 이 한 글자를 재현한다.",
            s,
            "title-typo.hwp",
            [replace_text("시정님", "시장님")],
            "짧은 find — 빈 문자열 금지 계약과 반대편",
        ),
        Scenario(
            "en_typo",
            "공문",
            "영문오탈",
            "recieve→receive",
            "영문 안내문 오탈. caseSensitive 기본 true 라 Recieve 는 안 바뀐다.",
            s,
            "en-typo.hwp",
            [replace_text("recieve", "receive", caseSensitive=True)],
            "대소문자 기본값 명시",
        ),
        Scenario(
            "form_name",
            "신청서",
            "누름틀",
            "성명 누름틀 채움",
            "서식 성명 칸. fill_fields 1 step. 필드 이름은 호출자 값이다.",
            f,
            "form-name.hwp",
            [fill_fields({"성명": "홍길동"})],
            "plan_schema fill_fields.data",
        ),
        Scenario(
            "form_rrn_mask",
            "신청서",
            "주민번호",
            "주민등록번호 누름틀에 마스킹 값",
            "실번호를 넣지 않고 마스킹 문자열을 넣는다. 영수증은 그 문자열의 "
            "산출 해시만 남긴다 — 원번호는 계획에도 없다.",
            f,
            "form-rrn.hwp",
            [fill_fields({"주민등록번호": "******-*******"})],
            "문서 원문이 아닌 호출자 마스킹 값",
        ),
        Scenario(
            "checkbox_agree",
            "신청서",
            "동의체크",
            "개인정보 수집 동의 체크",
            "set_checkbox 는 plan_schema 허용 action. 체크 한 칸이 1 step.",
            f,
            "checkbox-agree.hwp",
            [set_checkbox("개인정보수집동의", True)],
            "boolean checked",
        ),
        Scenario(
            "table_label",
            "표",
            "라벨",
            "일련번호 헤더 표기 정정",
            "표 헤더 문자열. replace_text 로 두되 표 좌표 편집(set_cell)과 구분.",
            t,
            "table-label.hwp",
            [replace_text("일련 번호", "일련번호")],
            "헤더는 본문 치환 축",
        ),
        Scenario(
            "cell_amount",
            "예산",
            "셀금액",
            "예산 표 (0,2,3) 칸에 금액",
            "set_cell 은 격자 주소 u16. 줄바꿈·탭 없는 한 줄 값.",
            t,
            "cell-amount.hwp",
            [set_cell(0, 2, 3, "12,500,000")],
            "plan_schema set_cell 한 줄 계약",
        ),
        Scenario(
            "seal_caption",
            "공문",
            "직인",
            "직인 캡션 (인) 유지",
            "직인 옆 캡션을 같은 값으로 치환. 원본 훼손 없는 결정론 표본.",
            s,
            "seal-caption.hwp",
            [replace_text("(인)", "(인)")],
            "idempotent",
        ),
        Scenario(
            "hwpx_year",
            "공문",
            "hwpx",
            "HWPX 본문 연도 2024→2026",
            "입력 확장자가 hwpx 면 스냅샷도 hwpx. 산출 확장자는 output 을 따른다.",
            x,
            "hwpx-year.hwpx",
            [replace_text("2024", "2026")],
            "ext=hwpx",
            ext="hwpx",
        ),
        Scenario(
            "newline_keep",
            "공문",
            "개행",
            "수신자 줄바꿈 뒤 기관명 치환",
            "find 에 개행을 넣지 않는다. 엔진은 본문 런 단위로 치환한다.",
            s,
            "newline-keep.hwp",
            [replace_text("수신자 행정안전부", "수신자 서울특별시")],
            "개행을 find 에 넣지 않는 것이 계약",
        ),
        Scenario(
            "privacy_mask",
            "보안",
            "전화마스킹",
            "02-2100-2114→02-****-2114",
            "배포 전 중간 네 자리 마스킹. 영수증은 마스킹된 산출 해시만 가진다.",
            s,
            "privacy-phone.hwp",
            [replace_text("02-2100-2114", "02-****-2114")],
            "inspect 석과 무관 — replace_text 만",
        ),
        Scenario(
            "version_tag",
            "공문",
            "문서버전",
            "문서 버전 v1.2→v1.3",
            "머리글 버전 태그. 작은 표기 변경도 3해시가 바뀐다.",
            s,
            "version-tag.hwp",
            [replace_text("v1.2", "v1.3")],
            "toolVersion 과 다른 축 — 문서 버전",
        ),
        Scenario(
            "date_korean",
            "공문",
            "한글일자",
            "2026년 3월 31일→2026년 4월 1일",
            "시행일 하루 연기. 한글 일자 표기는 ISO 와 다른 바이트다.",
            s,
            "date-korean.hwp",
            [replace_text("2026년 3월 31일", "2026년 4월 1일")],
            "한글 일자 축",
        ),
        Scenario(
            "honorific",
            "공문",
            "경칭",
            "귀하 유지",
            "수신 경칭은 보통 그대로 둔다. find==replace 결정론.",
            s,
            "honorific.hwp",
            [replace_text("귀하", "귀하")],
            "idempotent",
        ),
        Scenario(
            "sender_title",
            "공문",
            "발신명의",
            "경기도지사→경기도지사 직무대행",
            "직무대행 표기 추가. 문자열 길이가 늘어 산출 해시가 바뀐다.",
            s,
            "sender-title.hwp",
            [replace_text("경기도지사", "경기도지사 직무대행")],
            "접미사 추가",
        ),
        Scenario(
            "receiver_dept",
            "공문",
            "수신처",
            "수신 기획조정실→정책기획관",
            "수신처 직제명 변경. 발신 명의 변경과 축을 가른다.",
            s,
            "receiver-dept.hwp",
            [replace_text("기획조정실", "정책기획관")],
            "수신 축",
        ),
        Scenario(
            "via_line",
            "공문",
            "경유",
            "경유 감사담당관 추가 표기 정정",
            "경유 칸 오기를 고친다. 경유는 수신·발신과 다른 칸이다.",
            s,
            "via-line.hwp",
            [replace_text("경유 감사실", "경유 감사담당관")],
            "경유 축",
        ),
        Scenario(
            "subject_line",
            "공문",
            "제목",
            "제목: 협조 요청→제목: 자료 제출 요청",
            "제목 줄만 바꾼다. 본문 연도 치환과 분리.",
            s,
            "subject-line.hwp",
            [replace_text("제목: 협조 요청", "제목: 자료 제출 요청")],
            "제목 축",
        ),
        Scenario(
            "ref_number",
            "공문",
            "문서번호",
            "행안-2025-1234→행안-2026-0001",
            "연도 바뀌며 문서번호가 리셋된다. 본문 연도 치환과 다른 필드.",
            s,
            "ref-number.hwp",
            [replace_text("행안-2025-1234", "행안-2026-0001")],
            "문서번호 축",
        ),
        Scenario(
            "attach_count",
            "공문",
            "붙임",
            "붙임 1부.→붙임 2부.",
            "첨부 부수 정정. 쪽 참조(page_ref)와 다른 단위(부).",
            s,
            "attach-count.hwp",
            [replace_text("붙임 1부.", "붙임 2부.")],
            "부수 축",
        ),
        Scenario(
            "copy_to",
            "공문",
            "사본",
            "사본 수신 기획재정부 추가",
            "숨은참조/사본 수신처 문자열. 본문 수신과 구분.",
            s,
            "copy-to.hwp",
            [replace_text("사본 수신 없음", "사본 수신 기획재정부")],
            "사본 축",
        ),
        Scenario(
            "effective_date",
            "고시",
            "시행일",
            "이 고시는 고시한 날부터 시행한다 유지",
            "표준 시행 문장. find==replace 로 존재만 확인하는 결정론 표본.",
            s,
            "effective.hwp",
            [replace_text("고시한 날부터 시행한다", "고시한 날부터 시행한다")],
            "idempotent 고시 문장",
        ),
        Scenario(
            "expire_date",
            "고시",
            "유효기간",
            "유효기간 2026-12-31→2027-12-31",
            "일몰 조항 연장. deadline_iso 와 다른 필드(유효기간).",
            s,
            "expire.hwp",
            [replace_text("유효기간 2026-12-31", "유효기간 2027-12-31")],
            "일몰 축",
        ),
        Scenario(
            "budget_code",
            "예산",
            "과목",
            "예산과목 101-01→101-02",
            "세항 코드 정정. 금액 표기(amount_comma)와 축을 가른다.",
            t,
            "budget-code.hwp",
            [replace_text("101-01", "101-02")],
            "과목코드 축",
        ),
        Scenario(
            "account_mask",
            "보안",
            "계좌",
            "계좌 중간 마스킹",
            "110-123-456789→110-***-456789. 배포본에서만 쓰는 계획.",
            s,
            "account-mask.hwp",
            [replace_text("110-123-456789", "110-***-456789")],
            "계좌 마스킹",
        ),
        Scenario(
            "biz_no",
            "계약",
            "사업자번호",
            "사업자등록번호 하이픈 정규화",
            "1234567890→123-45-67890. 검증 체크섬은 엔진이 하지 않는다.",
            s,
            "biz-no.hwp",
            [replace_text("1234567890", "123-45-67890")],
            "표기만, 체크섬 없음",
        ),
        Scenario(
            "corp_name",
            "계약",
            "법인명",
            "(주)한빛→한빛 주식회사",
            "법인 표기 정규화. 약칭과 공식 표기가 다른 바이트다.",
            s,
            "corp-name.hwp",
            [replace_text("(주)한빛", "한빛 주식회사")],
            "법인 표기 축",
        ),
        Scenario(
            "bid_round",
            "입찰",
            "차수",
            "1차 입찰→2차 입찰",
            "유찰 후 차수 변경. 예정가격 필드와 분리.",
            s,
            "bid-round.hwp",
            [replace_text("1차 입찰", "2차 입찰")],
            "차수 축",
        ),
        Scenario(
            "bid_price",
            "입찰",
            "예정가격",
            "예정가격 표기 정정",
            "예정가격 9억→8억. 금액 콤마 케이스와 다른 문서 가족.",
            s,
            "bid-price.hwp",
            [replace_text("예정가격 900,000,000원", "예정가격 800,000,000원")],
            "입찰 금액 축",
        ),
        Scenario(
            "exam_year",
            "시험",
            "학년도",
            "2025학년도→2026학년도",
            "시험지 표지 학년도. HWPX 시험 샘플을 쓴다.",
            x,
            "exam-year.hwpx",
            [replace_text("2025학년도", "2026학년도")],
            "ext=hwpx",
            related=("#4391", "#5478"),
            ext="hwpx",
        ),
        Scenario(
            "exam_subject",
            "시험",
            "과목",
            "한국사→한국사(필수)",
            "표지 과목 표기. 학년도와 다른 필드.",
            x,
            "exam-subject.hwpx",
            [replace_text("과목: 한국사", "과목: 한국사(필수)")],
            "ext=hwpx",
            ext="hwpx",
        ),
        Scenario(
            "minutes_date",
            "회의록",
            "일시",
            "회의일시 정정",
            "2026-03-31 14:00→2026-03-31 15:00. 한 시간 연기.",
            s,
            "minutes-date.hwp",
            [replace_text("2026-03-31 14:00", "2026-03-31 15:00")],
            "시각 축",
        ),
        Scenario(
            "minutes_attend",
            "회의록",
            "출석",
            "출석 6인→출석 7인",
            "정족수 기록. 안건 번호와 분리.",
            s,
            "minutes-attend.hwp",
            [replace_text("출석 6인", "출석 7인")],
            "출석 축",
        ),
        Scenario(
            "agenda_item",
            "안건",
            "호수",
            "안건 제2호→제3호",
            "안건 번호 정정. 회의록 출석과 다른 문서 역할.",
            s,
            "agenda-item.hwp",
            [replace_text("안건 제2호", "안건 제3호")],
            "안건 호수",
        ),
        Scenario(
            "petition_no",
            "민원",
            "접수번호",
            "민원 접수번호 부여",
            "임시→민원-2026-00412. 처리결과 필드와 분리.",
            s,
            "petition-no.hwp",
            [replace_text("접수번호 임시", "접수번호 민원-2026-00412")],
            "접수번호 축",
        ),
        Scenario(
            "petition_result",
            "민원",
            "처리결과",
            "처리결과 검토중→수용",
            "종결 표기. 접수번호와 다른 칸.",
            s,
            "petition-result.hwp",
            [replace_text("처리결과 검토중", "처리결과 수용")],
            "처리결과 축",
        ),
        Scenario(
            "hr_order",
            "인사",
            "발령",
            "전보 발령 문구 정정",
            "전보→겸임. 직급 표기와 분리.",
            s,
            "hr-order.hwp",
            [replace_text("전보 발령", "겸임 발령")],
            "발령 종류",
        ),
        Scenario(
            "hr_grade",
            "인사",
            "직급",
            "서기관→부이사관",
            "승진 발령 직급. 발령 종류와 다른 필드.",
            s,
            "hr-grade.hwp",
            [replace_text("직급 서기관", "직급 부이사관")],
            "직급 축",
        ),
        Scenario(
            "statute_article",
            "법령",
            "조문",
            "제1조(목적) 표제 유지",
            "조문 표제는 보통 그대로. 인용 조문 번호 정정(law_ref)과 구분.",
            s,
            "statute-article.hwp",
            [replace_text("제1조(목적)", "제1조(목적)")],
            "idempotent 표제",
        ),
        Scenario(
            "statute_amend",
            "법령",
            "개정",
            "일부개정→전부개정",
            "개정 종류 표기. 조문 내용과 다른 메타 문자열.",
            s,
            "statute-amend.hwp",
            [replace_text("일부개정", "전부개정")],
            "개정 종류",
        ),
        Scenario(
            "registry_lot",
            "등기",
            "지번",
            "지번 123-4→123-5",
            "분할 후 지번. 소유자 필드와 분리.",
            s,
            "registry-lot.hwp",
            [replace_text("지번 123-4", "지번 123-5")],
            "지번 축",
        ),
        Scenario(
            "registry_owner",
            "등기",
            "소유자",
            "소유자 표시 정정",
            "홍길동→홍길동 외 1명. 지번과 다른 칸.",
            s,
            "registry-owner.hwp",
            [replace_text("소유자 홍길동", "소유자 홍길동 외 1명")],
            "소유자 축",
        ),
        Scenario(
            "audit_finding",
            "감사",
            "지적",
            "지적사항 제목 정정",
            "업무추진비 집행 부적정→정산 증빙 미비. 처분요구와 분리.",
            s,
            "audit-finding.hwp",
            [replace_text("업무추진비 집행 부적정", "정산 증빙 미비")],
            "지적 제목",
        ),
        Scenario(
            "audit_action",
            "감사",
            "처분",
            "처분요구 주의→시정",
            "처분 수위 변경. 지적 제목과 다른 필드.",
            s,
            "audit-action.hwp",
            [replace_text("처분요구 주의", "처분요구 시정")],
            "처분 수위",
        ),
        Scenario(
            "contract_party",
            "계약",
            "당사자",
            "갑 표시 정정",
            "갑: 서울특별시→갑: 서울특별시장. 법인명 케이스와 다른 칸.",
            s,
            "contract-party.hwp",
            [replace_text("갑: 서울특별시", "갑: 서울특별시장")],
            "당사자 축",
        ),
        Scenario(
            "contract_period",
            "계약",
            "기간",
            "계약기간 종료일 연장",
            "2026-12-31→2027-06-30. 고시 유효기간과 다른 문서 가족.",
            s,
            "contract-period.hwp",
            [replace_text("계약기간 2026-01-01 ~ 2026-12-31", "계약기간 2026-01-01 ~ 2027-06-30")],
            "계약기간 축",
        ),
        Scenario(
            "vat_include",
            "계약",
            "부가세",
            "부가세 별도→부가세 포함",
            "금액 해석이 바뀐다. 영수증은 그 문자열 바이트만 증명한다.",
            s,
            "vat-include.hwp",
            [replace_text("부가세 별도", "부가세 포함")],
            "부가세 표기",
        ),
        Scenario(
            "gazette_no",
            "고시",
            "관보",
            "관보 호수 정정",
            "제20788호→제20789호. 고시일자와 분리.",
            s,
            "gazette-no.hwp",
            [replace_text("관보 제20788호", "관보 제20789호")],
            "관보 호수",
        ),
        Scenario(
            "gazette_date",
            "고시",
            "고시일",
            "고시일자 정정",
            "고시일자 2026-03-30→2026-03-31. 관보 호수와 다른 필드.",
            s,
            "gazette-date.hwp",
            [replace_text("고시일자 2026-03-30", "고시일자 2026-03-31")],
            "고시일 축",
        ),
        Scenario(
            "form_date",
            "신청서",
            "작성일",
            "작성일자 누름틀",
            "fill_fields 작성일자. 성명 누름틀과 다른 필드 이름.",
            f,
            "form-date.hwp",
            [fill_fields({"작성일자": "2026-03-31"})],
            "날짜 누름틀",
        ),
        Scenario(
            "form_addr",
            "신청서",
            "주소칸",
            "주소 누름틀",
            "도로명 주소 한 줄. addr_fix(본문 치환)와 축이 다르다.",
            f,
            "form-addr.hwp",
            [fill_fields({"주소": "세종특별자치시 도움6로 11"})],
            "주소 누름틀",
        ),
        Scenario(
            "form_phone",
            "신청서",
            "전화칸",
            "전화번호 누름틀",
            "phone_hyphen(본문)과 달리 필드 값으로 넣는다.",
            f,
            "form-phone.hwp",
            [fill_fields({"전화번호": "02-2100-2114"})],
            "전화 누름틀",
        ),
        Scenario(
            "set_cell_name",
            "표",
            "성명셀",
            "표 (0,1,0) 성명 칸",
            "명단 표 성명. 금액 셀과 좌표·의미가 다르다.",
            t,
            "cell-name.hwp",
            [set_cell(0, 1, 0, "홍길동")],
            "성명 셀",
        ),
        Scenario(
            "set_cell_score",
            "시험",
            "점수셀",
            "점수 표 (0,4,2) = 85",
            "시험 점수 칸. 한 줄 숫자. 줄바꿈 거부 계약을 지킨다.",
            t,
            "cell-score.hwp",
            [set_cell(0, 4, 2, "85")],
            "점수 셀",
        ),
        Scenario(
            "checkbox_no",
            "신청서",
            "미동의",
            "선택 동의 해제",
            "checked=false. agree 케이스의 반대 축.",
            f,
            "checkbox-no.hwp",
            [set_checkbox("선택동의", False)],
            "false 체크",
        ),
        Scenario(
            "multi_notice",
            "공문",
            "다단계",
            "연도+부서 2 step",
            "steps=2 가 영수증 steps 와 같아야 한다. 감사는 길이 불일치를 잡는다.",
            s,
            "multi-notice.hwp",
            [replace_text("2025", "2026"), replace_text("총무과", "운영지원과")],
            "2-step 길이 계약",
        ),
        Scenario(
            "multi_form",
            "신청서",
            "채움+체크",
            "성명 채움 후 동의 체크",
            "fill_fields + set_checkbox. action 이 다른 2 step.",
            f,
            "multi-form.hwp",
            [fill_fields({"성명": "홍길동"}), set_checkbox("개인정보수집동의", True)],
            "이종 action 2-step",
        ),
        Scenario(
            "multi_table",
            "표",
            "세칸",
            "표 세 칸 연속 set_cell",
            "steps=3. 감사 steps 대조의 긴 쪽 표본.",
            t,
            "multi-table.hwp",
            [
                set_cell(0, 1, 0, "홍길동"),
                set_cell(0, 1, 1, "주무관"),
                set_cell(0, 1, 2, "02-2100-2114"),
            ],
            "3-step set_cell",
        ),
        Scenario(
            "occurrence_first",
            "공문",
            "순번",
            "첫 번째 2025 만 2026",
            "occurrence=0 은 첫 일치만. 전건 치환(notice_year)과 반대.",
            s,
            "occ-first.hwp",
            [replace_text("2025", "2026", occurrence=0)],
            "occurrence 0 기준",
        ),
        Scenario(
            "case_fold_off",
            "공문",
            "대소문자",
            "HWP 만 치환, hwp 는 남김",
            "caseSensitive=true 가 기본. 영문 약어 오용을 한 건만 고친다.",
            s,
            "case-off.hwp",
            [replace_text("HWP Viewer", "HWP 뷰어", caseSensitive=True)],
            "대소문자 구별",
        ),
        Scenario(
            "delete_draft",
            "공문",
            "삭제",
            "초안 표기 삭제",
            "replace 빈 문자열 = 삭제. find 는 비면 안 된다.",
            s,
            "delete-draft.hwp",
            [replace_text("[초안]", "")],
            "빈 replace 허용, 빈 find 금지",
        ),
        Scenario(
            "fullwidth_year",
            "공문",
            "전각",
            "전각 연도 ２０２５→2026",
            "전각 숫자는 반각과 다른 바이트. NFC 와도 다른 축.",
            s,
            "fullwidth-year.hwp",
            [replace_text("２０２５", "2026")],
            "전각 숫자",
        ),
        Scenario(
            "middle_dot",
            "법령",
            "가운뎃점",
            "법령명 가운뎃점 정규화",
            "· 와 ㆍ 는 다른 코드포인트. 법령 표기 정본을 고른다.",
            s,
            "middle-dot.hwp",
            [replace_text("개인정보 보호법", "개인정보·보호법")],
            "가운뎃점 축",
        ),
        Scenario(
            "tilde_range",
            "공문",
            "범위",
            "1~3쪽→1-3쪽",
            "물결표를 하이픈 범위로. page_ref 단일 쪽과 다른 표기.",
            s,
            "tilde-range.hwp",
            [replace_text("1~3쪽", "1-3쪽")],
            "범위 표기",
        ),
        Scenario(
            "won_symbol",
            "예산",
            "원화",
            "원→₩ 표기 통일 거부하고 '원' 유지",
            "원화 기호를 바꾸지 않는 결정론 표본. 금액 콤마와 다른 축.",
            t,
            "won-keep.hwp",
            [replace_text("원", "원")],
            "idempotent 원화",
        ),
        Scenario(
            "percent_rate",
            "계약",
            "이율",
            "연 3.0%→연 3.5%",
            "이율 한 칸. 부가세 표기와 다른 숫자 축.",
            s,
            "percent-rate.hwp",
            [replace_text("연 3.0%", "연 3.5%")],
            "이율 축",
        ),
        Scenario(
            "footnote_star",
            "공문",
            "각주",
            "각주 * 표기 유지",
            "각주 표식은 본문 문자열. 렌더 각주 레이아웃 석과 무관.",
            s,
            "footnote-star.hwp",
            [replace_text("* 자세한 사항은 붙임", "* 자세한 사항은 붙임")],
            "idempotent 각주 표식",
        ),
        Scenario(
            "header_org",
            "공문",
            "머릿글",
            "머릿글 기관명 개칭",
            "머릿글만 행정안전부. 본문 org_rename 과 위치가 다르다.",
            s,
            "header-org.hwp",
            [replace_text("머릿글 안전행정부", "머릿글 행정안전부")],
            "머릿글 축",
        ),
        Scenario(
            "form_indexed",
            "신청서",
            "반복필드",
            "같은 이름 13번째 칸",
            "이름[13] 문법. plan_schema 가 명시한 반복 필드 지목.",
            f,
            "form-indexed.hwp",
            [fill_fields({"피규제집단명[13]": "한국위생용품공업협동조합"})],
            "반복 필드 순번",
        ),
        Scenario(
            "keep_style_cell",
            "표",
            "스타일유지",
            "칸 값만 바꾸고 스타일 유지",
            "keepStyle 은 set_cell 선택 필드. 값만 바뀌는 계약.",
            t,
            "keep-style.hwp",
            [
                {
                    "action": "set_cell",
                    "table": 0,
                    "row": 0,
                    "col": 1,
                    "text": "합계",
                    "keepStyle": True,
                }
            ],
            "keepStyle true",
        ),
    ]


SCENARIOS: list[Scenario] = _scenarios()


def _exceptions() -> list[ExceptionSpec]:
    return [
        ExceptionSpec(
            "replay_no_args",
            "replay",
            ["replay"],
            2,
            0,
            "사용법: rhwp replay",
            (),
            "계획 위치 인자도 --plan-json 도 없으면 사용법. stdout 0바이트.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_unknown_flag",
            "replay",
            ["replay", "--nope"],
            2,
            0,
            "알 수 없는 옵션",
            (),
            "미지 플래그는 usage. 엔진을 타기 전에 끊는다.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_plan_json_missing",
            "replay",
            ["replay", "--plan-json"],
            2,
            0,
            "--plan-json 뒤에 계획 JSON 이 필요합니다",
            (),
            "플래그만 있고 값이 없다.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_expect_missing",
            "replay",
            ["replay", "--plan-json", "{}", "--expect-output-sha256"],
            2,
            0,
            "--expect-output-sha256 뒤에 64자리 16진 해시가 필요합니다",
            (),
            "verify 플래그 값 누락.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_expect_short",
            "replay",
            ["replay", "--plan-json", '{"input":"x.hwp","output":"y.hwp","steps":[]}', "--expect-output-sha256", "abc", "--json"],
            2,
            0,
            "--expect-output-sha256 값은 64자리 16진이어야 합니다",
            (),
            "replay_contract malformed_expected_hash. 짧은 값.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_expect_not_hex",
            "replay",
            ["replay", "--plan-json", '{"input":"x.hwp","output":"y.hwp","steps":[]}', "--expect-output-sha256", "g" * 64, "--json"],
            2,
            0,
            "--expect-output-sha256 값은 64자리 16진이어야 합니다",
            (),
            "64자지만 16진이 아님.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_parent_missing",
            "replay",
            ["replay", "--parent"],
            2,
            0,
            "--parent 뒤에 부모 캡슐 경로가 필요합니다",
            (),
            "체인 플래그 값 누락.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_capsule_missing",
            "replay",
            ["replay", "--capsule"],
            2,
            0,
            "--capsule 뒤에 저장 경로가 필요합니다",
            (),
            "캡슐 경로 누락.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_sign_key_missing",
            "replay",
            ["replay", "--sign-key"],
            2,
            0,
            "--sign-key 뒤에 키 파일 경로가 필요합니다",
            (),
            "서명 키 경로 누락.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_sign_without_capsule",
            "replay",
            ["replay", "--plan-json", "{}", "--sign-key", "k.json"],
            2,
            0,
            "--sign-key 는 --capsule 과 함께 사용합니다",
            (),
            "서명 대상은 캡슐 파일 바이트. 캡슐 없이 서명 금지.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_plan_parse",
            "replay",
            ["replay", "--plan-json", "{", "--json"],
            2,
            0,
            "계획 JSON 파싱 실패",
            (),
            "깨진 JSON 은 usage. 엔진 진입 전.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_plan_no_input",
            "replay",
            ["replay", "--plan-json", '{"output":"y.hwp","steps":[]}', "--json"],
            2,
            0,
            "계획에 input 이 필요합니다",
            (),
            "input 키 없음.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_same_file",
            "replay",
            ["replay", "--plan-json", '{"input":"x.hwp","output":"y.hwp","steps":[]}', "--capsule", "a.capsule.json", "--parent", "a.capsule.json"],
            2,
            0,
            "--capsule과 --parent가 같은 기존 파일을 가리킵니다",
            (),
            "부모 덮어쓰기 방지. 파일이 이미 있을 때만 발동.",
            "replay-usage",
        ),
        ExceptionSpec(
            "replay_plan_read",
            "replay",
            ["replay", "definitely_missing_plan.json"],
            1,
            0,
            "계획을 읽을 수 없습니다",
            (),
            "위치 인자 계획 파일 IO. exit 1.",
            "replay-io",
        ),
        ExceptionSpec(
            "replay_parent_read",
            "replay",
            ["replay", "--plan-json", '{"input":"x.hwp","output":"y.hwp","steps":[]}', "--capsule", "b.capsule.json", "--parent", "missing-parent.capsule.json"],
            1,
            0,
            "부모 캡슐을 읽을 수 없습니다",
            (),
            "canonicalize 실패. 부모 없음은 IO.",
            "replay-io",
        ),
        ExceptionSpec(
            "replay_engine_json",
            "replay",
            ["replay", "--plan-json", '{"input":"missing-input.hwp","output":"y.hwp","steps":[]}', "--json"],
            1,
            -1,
            "입력을 읽을 수 없습니다",
            ("schemaVersion", "error"),
            "엔진/입력 IO 는 --json 이면 {error} 봉투. 성공 영수증 키가 없다.",
            "replay-io",
        ),
        ExceptionSpec(
            "replay_verify_mismatch",
            "replay",
            ["replay", "--plan-json", "{plan}", "--expect-output-sha256", "0" * 64, "--json"],
            3,
            -1,
            "",
            ("schemaVersion", "mode", "reproduced", "expectedOutputSha256", "outputSha256"),
            "주장이 틀린다. reproduced:false, exit 3. 도구 고장이 아니다.",
            "replay-judgment",
        ),
        ExceptionSpec(
            "audit_no_args",
            "audit",
            ["audit"],
            2,
            0,
            "사용법: rhwp audit",
            (),
            "폴더 인자 없음.",
            "audit-usage",
        ),
        ExceptionSpec(
            "audit_unknown_flag",
            "audit",
            ["audit", "capsules", "--nope"],
            2,
            0,
            "알 수 없는 옵션",
            (),
            "미지 플래그.",
            "audit-usage",
        ),
        ExceptionSpec(
            "audit_empty",
            "audit",
            ["audit", "empty-dir", "--json"],
            2,
            0,
            "에 *.capsule.json 이 없습니다",
            (),
            "audit_contract empty_dir. stdout 0바이트.",
            "audit-usage",
        ),
        ExceptionSpec(
            "audit_dir_read",
            "audit",
            ["audit", "definitely_missing_dir", "--json"],
            1,
            0,
            "폴더를 읽을 수 없습니다",
            (),
            "없는 폴더는 IO. 빈 폴더(usage)와 가른다.",
            "audit-io",
        ),
        ExceptionSpec(
            "audit_kind",
            "audit",
            ["audit", "layouts/wrong-kind", "--json"],
            3,
            -1,
            "kind 가 workCapsule 이 아님",
            ("schemaVersion", "total", "reproduced", "failed", "reproducedRate"),
            "확장자만 맞은 JSON 은 회계 실패로 잡힌다.",
            "audit-judgment",
        ),
        ExceptionSpec(
            "audit_output_sha",
            "audit",
            ["audit", "layouts/bad-output-sha", "--json"],
            3,
            -1,
            "receipt.outputSha256 가 없거나 64자리 16진이 아님",
            ("schemaVersion", "failed"),
            "출력 해시 기형.",
            "audit-judgment",
        ),
        ExceptionSpec(
            "audit_input_sha",
            "audit",
            ["audit", "layouts/bad-input-sha", "--json"],
            3,
            -1,
            "receipt.inputSha256 가 없거나 64자리 16진이 아님",
            ("schemaVersion", "failed"),
            "입력 해시 기형. 산출 대조 전에 끊는다.",
            "audit-judgment",
        ),
        ExceptionSpec(
            "audit_plan_vs_text",
            "audit",
            ["audit", "layouts/plan-vs-text", "--json"],
            3,
            -1,
            "plan 과 planText 불일치",
            ("schemaVersion", "failed"),
            "parsed plan 만 바꾼 변조. 산출이 같아도 실패.",
            "audit-judgment",
        ),
        ExceptionSpec(
            "audit_plan_text_sha",
            "audit",
            ["audit", "layouts/plan-text-sha", "--json"],
            3,
            -1,
            "planText 와 receipt.planSha256 불일치",
            ("schemaVersion", "failed"),
            "plan 과 planText 를 같이 바꿔도 원문 해시가 폭로한다.",
            "audit-judgment",
        ),
        ExceptionSpec(
            "audit_steps",
            "audit",
            ["audit", "layouts/steps-tamper", "--json"],
            3,
            -1,
            "receipt.steps 와 planText.steps 길이 불일치 (plan.steps 길이와 receipt.steps 불일치)",
            ("schemaVersion", "failed"),
            "steps 필드만 999 로.",
            "audit-judgment",
        ),
        ExceptionSpec(
            "audit_mixed_rate",
            "audit",
            ["audit", "layouts/mixed", "--json"],
            3,
            -1,
            "",
            ("schemaVersion", "total", "reproduced", "failed", "reproducedRate"),
            "2/3 재현. rate=reproduced/total. 실패 1건 = exit 3.",
            "audit-judgment",
        ),
        ExceptionSpec(
            "lineage_no_args",
            "lineage",
            ["lineage"],
            2,
            0,
            "사용법: rhwp lineage",
            (),
            "머리 캡슐 없음 = usage.",
            "lineage-usage",
        ),
        ExceptionSpec(
            "lineage_unknown_flag",
            "lineage",
            ["lineage", "a.capsule.json", "--nope"],
            2,
            0,
            "알 수 없는 옵션",
            (),
            "lineage_contract 미지 옵션.",
            "lineage-usage",
        ),
        ExceptionSpec(
            "lineage_keyring_missing",
            "lineage",
            ["lineage", "a.capsule.json", "--keyring"],
            2,
            0,
            "--keyring 뒤에 키 등록부 경로가 필요합니다",
            (),
            "opt-in 서명 축 플래그 값 누락.",
            "lineage-usage",
        ),
        ExceptionSpec(
            "lineage_anchor_missing",
            "lineage",
            ["lineage", "a.capsule.json", "--anchor-log"],
            2,
            0,
            "--anchor-log 뒤에 로그 경로가 필요합니다",
            (),
            "opt-in 앵커 축 플래그 값 누락.",
            "lineage-usage",
        ),
        ExceptionSpec(
            "lineage_head_missing",
            "lineage",
            ["lineage", "definitely_missing.capsule.json", "--json"],
            1,
            0,
            "캡슐을 읽을 수 없습니다",
            (),
            "머리 없음은 IO exit 1. 깨진 체인(exit 3)과 가른다.",
            "lineage-io",
        ),
        ExceptionSpec(
            "lineage_parent_field",
            "lineage",
            ["lineage", "no-parent-field.capsule.json", "--json"],
            3,
            -1,
            "parent 필드 없음",
            ("schemaVersion", "valid", "brokenAt", "links"),
            "parent 키 자체 없음은 root 가 아니다. fail-closed.",
            "lineage-judgment",
        ),
        ExceptionSpec(
            "lineage_parent_sha",
            "lineage",
            ["lineage", "no-parent-sha.capsule.json", "--json"],
            3,
            -1,
            "parent.sha256 가 없거나 64자리 16진이 아님",
            ("schemaVersion", "valid", "brokenAt"),
            "링크 해시 누락은 검증 생략이 아니라 즉시 실패.",
            "lineage-judgment",
        ),
        ExceptionSpec(
            "lineage_parent_tamper",
            "lineage",
            ["lineage", "b.capsule.json", "--json"],
            3,
            -1,
            "",
            ("schemaVersion", "valid", "brokenAt", "links"),
            "부모 파일 사후 변조 → parentOk:false, brokenAt=부모.",
            "lineage-judgment",
        ),
        ExceptionSpec(
            "lineage_invariant",
            "lineage",
            ["lineage", "child-wrong-input.capsule.json", "--json"],
            3,
            -1,
            "",
            ("schemaVersion", "valid", "brokenAt"),
            "부모 산출 ≠ 자식 입력 → lineageOk:false.",
            "lineage-judgment",
        ),
        ExceptionSpec(
            "lineage_kind",
            "lineage",
            ["lineage", "not-capsule.json", "--json"],
            3,
            -1,
            "kind 가 workCapsule 이 아님",
            ("schemaVersion", "valid", "brokenAt"),
            "JSON 이지만 캡슐이 아님.",
            "lineage-judgment",
        ),
    ]


EXCEPTIONS: list[ExceptionSpec] = _exceptions()


def _audit_layouts() -> list[AuditLayout]:
    return [
        AuditLayout(
            "empty",
            "빈 폴더",
            "직속 *.capsule.json 0개 = usage exit 2, stdout 0바이트.",
            (),
            ("notes.txt",),
            0,
            0,
            (),
            2,
            "audit_contract empty_dir",
        ),
        AuditLayout(
            "all-ok",
            "전건 재현",
            "직속 캡슐 3개가 모두 재현. rate=1.0, exit 0.",
            ("notice_year", "org_rename", "dept_rename"),
            ("notes.txt",),
            3,
            3,
            (),
            0,
            "성공 회계",
        ),
        AuditLayout(
            "mixed",
            "2/3 재현",
            "출력 해시 변조 1건. total=3 reproduced=2 rate=2/3 exit 3.",
            ("notice_year", "org_rename", "tamper_output"),
            (),
            3,
            2,
            ("outputSha256",),
            3,
            "실패한 1건만 failed[]",
        ),
        AuditLayout(
            "all-fail",
            "전건 실패",
            "세 가지 변조(출력·입력·steps). reproduced=0 rate=0.",
            ("tamper_output", "tamper_input", "tamper_steps"),
            (),
            3,
            0,
            ("outputSha256", "inputSha256", "steps"),
            3,
            "실패 종류 3종",
        ),
        AuditLayout(
            "nested-ignored",
            "비재귀",
            "nested/hidden.capsule.json 은 세지 않는다. 직속 1개만 total.",
            ("notice_year",),
            ("nested/hidden.capsule.json",),
            1,
            1,
            (),
            0,
            "collect_audit_capsules 비재귀",
        ),
        AuditLayout(
            "mixed-ext",
            "확장자 필터",
            ".bak .txt .json 은 대상이 아니다. ends_with .capsule.json 만.",
            ("notice_year",),
            ("keep.capsule.json.bak", "keep.capsule.json.txt", "notes.json"),
            1,
            1,
            (),
            0,
            "파일 이름 접미사",
        ),
        AuditLayout(
            "plan-vs-text",
            "plan 변조",
            "output 경로만 바꾼 parsed plan. 산출이 같아도 plan≠planText.",
            ("tamper_plan",),
            (),
            1,
            0,
            ("plan_vs_text",),
            3,
            "output-neutral tamper",
        ),
        AuditLayout(
            "plan-text-sha",
            "원문 해시",
            "plan 과 planText 를 같이 바꿔도 receipt.planSha256 이 폭로.",
            ("tamper_plan_text",),
            (),
            1,
            0,
            ("plan_text_sha",),
            3,
            "원문 해시 불변",
        ),
        AuditLayout(
            "steps-tamper",
            "step 수 변조",
            "receipt.steps=999. 길이 불일치 바늘.",
            ("tamper_steps",),
            (),
            1,
            0,
            ("steps",),
            3,
            "steps 길이",
        ),
        AuditLayout(
            "wrong-kind",
            "kind 오류",
            "kind=note 인 JSON. 확장자만 맞음.",
            ("wrong_kind",),
            (),
            1,
            0,
            ("kind",),
            3,
            "kind 가드",
        ),
        AuditLayout(
            "bad-output-sha",
            "출력 해시 기형",
            "outputSha256=xyz. 64hex 가드.",
            ("bad_output_sha",),
            (),
            1,
            0,
            ("output_sha",),
            3,
            "hex 가드",
        ),
        AuditLayout(
            "bad-input-sha",
            "입력 해시 기형",
            "inputSha256 누락. 산출 대조 전 실패.",
            ("bad_input_sha",),
            (),
            1,
            0,
            ("input_sha",),
            3,
            "입력 가드",
        ),
        AuditLayout(
            "invalid-json",
            "깨진 JSON",
            "파싱 실패는 failed[] 사유. 폴더 전체 회계는 계속.",
            ("invalid_json",),
            (),
            1,
            0,
            ("json",),
            3,
            "한 건 파싱 실패",
        ),
        AuditLayout(
            "same-folder-chain",
            "같은 폴더 체인",
            "부모·자식이 한 폴더. audit 는 체인을 따라가지 않고 각각 재실행.",
            ("notice_year", "chain_child"),
            (),
            2,
            2,
            (),
            0,
            "audit ≠ lineage",
        ),
        AuditLayout(
            "rate-1-of-4",
            "1/4",
            "재현 1, 실패 3. rate=0.25.",
            ("notice_year", "tamper_output", "tamper_input", "tamper_steps"),
            (),
            4,
            1,
            ("outputSha256", "inputSha256", "steps"),
            3,
            "분수 회계",
        ),
        AuditLayout(
            "rate-3-of-4",
            "3/4",
            "재현 3, 실패 1. rate=0.75.",
            ("notice_year", "org_rename", "dept_rename", "tamper_output"),
            (),
            4,
            3,
            ("outputSha256",),
            3,
            "한 건이 전체를 3으로",
        ),
        AuditLayout(
            "single",
            "단건",
            "캡슐 1개 전건 재현. rate=1.0.",
            ("notice_year",),
            (),
            1,
            1,
            (),
            0,
            "최소 성공 폴더",
        ),
        AuditLayout(
            "pretty-print",
            "포맷터 변조",
            "에디터가 공백을 넣으면 부모 해시가 깨진다. audit 는 재실행이라 "
            "계획만 같으면 통과할 수 있다 — lineage parentOk 와 다른 축.",
            ("pretty_print",),
            (),
            1,
            1,
            (),
            0,
            "audit 는 파일 바이트가 아니라 재실행",
        ),
        AuditLayout(
            "missing-plan-text",
            "planText 없음",
            "planText 키 삭제. validated_capsule_plan 첫 가드.",
            ("missing_plan_text",),
            (),
            1,
            0,
            ("plan_text_missing",),
            3,
            "planText 가드",
        ),
        AuditLayout(
            "toolversion-mismatch",
            "도구 버전 기록",
            "receipt.toolVersion 이 다른 값은 audit 실패 조건이 아니다. "
            "재실행 해시만 본다. 스킬 pitfalls 가 선대조를 요구하는 이유.",
            ("toolversion_other",),
            (),
            1,
            1,
            (),
            0,
            "toolVersion 은 힌트이지 가드가 아님",
        ),
    ]


AUDIT_LAYOUTS: list[AuditLayout] = _audit_layouts()


def _lineage() -> list[LineageTopo]:
    def link(
        name: str,
        parent_ok: bool | None,
        lineage_ok_v: bool | None,
        reproduced: bool | None,
        error: str | None = None,
    ) -> dict[str, Any]:
        return {
            "capsule": name,
            "parentOk": parent_ok,
            "lineageOk": lineage_ok_v,
            "reproduced": reproduced,
            "error": error,
        }

    return [
        LineageTopo(
            "root",
            "뿌리 하나",
            "parent=null 인 머리. depth=1, 판정 3축은 전부 null, valid=true.",
            1,
            True,
            None,
            False,
            0,
            (link("a.capsule.json", None, None, None),),
            "뿌리도 계보다",
        ),
        LineageTopo(
            "two-link",
            "2링크 유효",
            "부모 산출=자식 입력. parentOk·lineageOk true. brokenAt null.",
            2,
            True,
            None,
            False,
            0,
            (
                link("b.capsule.json", True, True, None),
                link("a.capsule.json", None, None, None),
            ),
            "연대기 정의",
        ),
        LineageTopo(
            "three-link",
            "3링크 유효",
            "A→B→C. 각 링크마다 부모 산출=자식 입력.",
            3,
            True,
            None,
            False,
            0,
            (
                link("c.capsule.json", True, True, None),
                link("b.capsule.json", True, True, None),
                link("a.capsule.json", None, None, None),
            ),
            "깊이 3",
        ),
        LineageTopo(
            "five-link",
            "5링크 유효",
            "긴 체인. depth=links.len().",
            5,
            True,
            None,
            False,
            0,
            tuple(
                link(f"{chr(97+i)}.capsule.json", None if i == 4 else True, None if i == 4 else True, None)
                for i in range(5)
            ),
            "깊이 5 — 머리부터 뿌리 순서로 기록",
        ),
        LineageTopo(
            "deep-ok",
            "--deep 전건 재현",
            "링크마다 임시 재실행. reproduced=true. 비용=링크 수.",
            2,
            True,
            None,
            True,
            0,
            (
                link("b.capsule.json", True, True, True),
                link("a.capsule.json", None, None, True),
            ),
            "deep 축",
        ),
        LineageTopo(
            "parent-tamper",
            "부모 파일 변조",
            "자식이 기록한 부모 파일 해시 ≠ 실물. parentOk=false, brokenAt=부모.",
            2,
            False,
            "parentOk",
            False,
            3,
            (
                link("b.capsule.json", True, True, None),
                link("a.capsule.json", False, True, None),
            ),
            "사후 변조 폭로",
        ),
        LineageTopo(
            "lineage-break",
            "연대기 불변 깨짐",
            "부모 산출 해시 ≠ 자식 입력 해시. lineageOk=false.",
            2,
            False,
            "lineageOk",
            False,
            3,
            (
                link("b.capsule.json", True, False, None),
                link("a.capsule.json", None, None, None),
            ),
            "다른 파일을 입력으로 씀",
        ),
        LineageTopo(
            "missing-parent-sha",
            "parent.sha256 누락",
            "검증 생략이 아니라 머리에서 즉시 실패.",
            1,
            False,
            "parent.sha256",
            False,
            3,
            (link("b.capsule.json", None, None, None, "parent.sha256 가 없거나 64자리 16진이 아님"),),
            "fail-closed",
        ),
        LineageTopo(
            "missing-parent-field",
            "parent 키 없음",
            "합법 root(null) 와 다르다. 필드 자체가 없으면 실패.",
            1,
            False,
            "parent",
            False,
            3,
            (link("b.capsule.json", None, None, None, "parent 필드 없음"),),
            "root 오인 금지",
        ),
        LineageTopo(
            "missing-parent-capsule",
            "parent.capsule 없음",
            "parent 객체는 있으나 경로 키 없음.",
            1,
            False,
            "parent.capsule",
            False,
            3,
            (link("b.capsule.json", None, None, None, "parent.capsule 없음"),),
            "경로 키",
        ),
        LineageTopo(
            "missing-plan-sha",
            "planSha256 누락",
            "shallow 도 계획 해시를 검사한다.",
            1,
            False,
            "planSha256",
            False,
            3,
            (link("b.capsule.json", None, None, None, "receipt.planSha256 가 없거나 64자리 16진이 아님"),),
            "shallow fail-closed",
        ),
        LineageTopo(
            "plan-vs-text",
            "plan 변조",
            "plan.steps=[] 로 바꿈. plan 과 planText 불일치.",
            1,
            False,
            "plan_vs_text",
            False,
            3,
            (link("b.capsule.json", None, None, None, "plan 과 planText 불일치"),),
            "shallow 계획 가드",
        ),
        LineageTopo(
            "steps-tamper",
            "steps 변조",
            "receipt.steps=999. 길이 바늘.",
            1,
            False,
            "steps",
            False,
            3,
            (
                link(
                    "b.capsule.json",
                    None,
                    None,
                    None,
                    "receipt.steps 와 planText.steps 길이 불일치 (plan.steps 길이와 receipt.steps 불일치)",
                ),
            ),
            "shallow steps",
        ),
        LineageTopo(
            "wrong-kind",
            "kind 오류",
            "workCapsule 이 아님.",
            1,
            False,
            "kind",
            False,
            3,
            (link("note.json", None, None, None, "kind 가 workCapsule 이 아님"),),
            "kind 가드",
        ),
        LineageTopo(
            "bad-input-sha",
            "입력 해시 기형",
            "inputSha256 가드. 64hex 아니면 즉시 실패.",
            1,
            False,
            "inputSha256",
            False,
            3,
            (link("b.capsule.json", None, None, None, "receipt.inputSha256 가 없거나 64자리 16진이 아님"),),
            "입력 가드",
        ),
        LineageTopo(
            "bad-output-sha",
            "출력 해시 기형",
            "outputSha256 가드.",
            1,
            False,
            "outputSha256",
            False,
            3,
            (link("b.capsule.json", None, None, None, "receipt.outputSha256 가 없거나 64자리 16진이 아님"),),
            "출력 가드",
        ),
        LineageTopo(
            "relative-parent",
            "상대 경로 부모",
            "parent.capsule 은 캡슐 파일 기준 상대. cwd 가 아니다.",
            2,
            True,
            None,
            False,
            0,
            (
                link("sub/b.capsule.json", True, True, None),
                link("sub/a.capsule.json", None, None, None),
            ),
            "상대 경로 해석",
        ),
        LineageTopo(
            "missing-parent-file",
            "부모 파일 없음",
            "머리 이후 부모 읽기 실패는 체인 깨짐(exit 3). 머리 없음(exit 1)과 가른다.",
            2,
            False,
            "parent_read",
            False,
            3,
            (
                link("b.capsule.json", True, True, None),
                link("missing.capsule.json", None, None, None, "부모 캡슐 읽기 실패"),
            ),
            "중간 IO 는 판단 실패",
        ),
        LineageTopo(
            "deep-fail",
            "--deep 재현 실패",
            "shallow 는 통과, deep 재실행 해시 불일치. reproduced=false.",
            2,
            False,
            "reproduced",
            True,
            3,
            (
                link("b.capsule.json", True, True, False),
                link("a.capsule.json", None, None, None),
            ),
            "deep 축 실패",
        ),
        LineageTopo(
            "no-keyring",
            "키링 없음",
            "--keyring 없으면 signerOk 축 자체가 없다. 기존 소비자 호환.",
            1,
            True,
            None,
            False,
            0,
            (link("a.capsule.json", None, None, None),),
            "서명 축 opt-in",
        ),
        LineageTopo(
            "head-missing",
            "머리 파일 없음",
            "exit 1, stdout 0. 봉투 없음.",
            0,
            False,
            "head_io",
            False,
            1,
            (),
            "IO vs 판단",
        ),
        LineageTopo(
            "usage",
            "인자 없음",
            "exit 2, stdout 0.",
            0,
            False,
            "usage",
            False,
            2,
            (),
            "usage",
        ),
    ]


LINEAGE: list[LineageTopo] = _lineage()


def scenario_by_id(ident: str) -> Scenario:
    for item in SCENARIOS:
        if item.ident == ident:
            return item
    raise KeyError(ident)
