#!/usr/bin/env python3
"""Real 누름틀 inventories for fields / fill-fields / batch fill fixtures.

Names come from shipped samples, 별지 서식, and the administrative forms
already cited by form_filling_guide / recipes / tools/forms. Repeated
names are listed once per occurrence so ``이름[N]`` order matches
``fields --json``.
"""

from __future__ import annotations

from form_fill import FieldRec, FormCatalog


def F(
    name: str,
    guide: str = "",
    value: str = "",
    *,
    memo: str = "",
    paragraph: int = 0,
    nested: tuple[str, ...] = (),
    field_id: int = 0,
) -> FieldRec:
    return FieldRec(
        name=name,
        guide=guide,
        value=value,
        memo=memo,
        paragraph=paragraph,
        nested=nested,
        field_id=field_id,
    )


def repeat(name: str, count: int, guide: str, *, start_para: int) -> list[FieldRec]:
    return [
        F(name, f"{guide} ({index + 1}/{count})", "", paragraph=start_para + index)
        for index in range(count)
    ]


def _gian() -> list[FieldRec]:
    names = [
        ("행정기관명", "발신 행정기관"),
        ("수신자", "수신 기관·직위"),
        ("경유", "경유 기관, 없으면 비움"),
        ("제목", "문서 제목"),
        ("본문", "본문 항목체계"),
        ("붙임", "붙임 문서명"),
        ("발신명의", "발신 명의"),
        ("수신자명단", "수신자 참조 명단"),
        ("기안자", "기안자 직위·성명"),
        ("검토자", "검토자 직위·성명"),
        ("결재권자", "결재권자 직위·성명"),
        ("협조자", "협조 부서·성명"),
        ("시행번호", "생산등록번호"),
        ("시행일", "시행 연월일"),
        ("접수번호", "접수번호"),
        ("접수일", "접수 연월일"),
        ("우편번호", "우편번호"),
        ("주소", "발신 기관 주소"),
        ("홈페이지", "기관 홈페이지"),
        ("전화번호", "담당 전화"),
        ("팩스번호", "담당 팩스"),
        ("전자우편", "담당 전자우편"),
        ("공개구분", "공개·부분공개·비공개"),
    ]
    return [F(name, guide, "", paragraph=index) for index, (name, guide) in enumerate(names)]


def _gani() -> list[FieldRec]:
    names = [
        ("생산등록번호", "문서등록표 생산번호"),
        ("등록일", "문서등록표 등록일"),
        ("결재일", "문서등록표 결재일"),
        ("공개구분", "공개 구분"),
        ("직위1", "결재란 1칸 직위"),
        ("직위2", "결재란 2칸 직위"),
        ("직위3", "결재란 3칸 직위"),
        ("직위4", "결재란 4칸 직위"),
        ("협조자", "결재란 협조 병합행"),
        ("제목", "내부결재 제목"),
        ("요약설명", "점선 박스 요약"),
        ("작성일", "작성 연월일"),
        ("작성기관", "작성 부서"),
    ]
    return [F(name, guide, "", paragraph=index) for index, (name, guide) in enumerate(names)]


def _regulatory() -> list[FieldRec]:
    head = [
        F("서식명", "규제영향분석서", "규제영향분석서", paragraph=0),
        F("법령명", "대상 법령명", "", paragraph=1),
        F("소관부처", "소관 중앙행정기관", "", paragraph=2),
        F("작성일자", "작성 연월일", "", paragraph=3),
        F("작성자", "작성 담당자", "", paragraph=4),
        F("연락처", "담당 전화", "", paragraph=5),
        F("규제목적", "규제 목적 요약", "", paragraph=6),
        F("규제내용", "규제 내용 요지", "", paragraph=7),
    ]
    groups = repeat("피규제집단명", 14, "피규제 집단", start_para=8)
    tail = [
        F("대안비교", "대안의 비교", "", paragraph=22),
        F("비용편익", "비용·편익 요약", "", paragraph=23),
        F("의견수렴", "의견수렴 결과", "", paragraph=24),
        F("일몰설정", "일몰 조항", "", paragraph=25),
        F("검토자", "검토 책임자", "", paragraph=26),
        F("결재권자", "결재권자", "", paragraph=27),
    ]
    return head + groups + tail


def _field01() -> list[FieldRec]:
    fields = [
        F("회사명", "회사명을 입력하십시오", "", paragraph=0),
        F("작성자", "작성자 성명", "", paragraph=1),
        F("부서명", "소속 부서", "", paragraph=2),
        F("전화번호", "연락 전화", "", paragraph=3),
        F("이메일", "전자우편", "", paragraph=4),
        F("제목", "문서 제목", "", paragraph=5),
    ]
    fields.extend(repeat("목차1", 5, "목차 항목", start_para=6))
    return fields


def FORMS() -> tuple[FormCatalog, ...]:
    forms: list[FormCatalog] = [
        FormCatalog(
            ident="field-01",
            title="누름틀 11개 혼합 샘플",
            family="sample",
            genre="계약 정본",
            sample="samples/field-01.hwp",
            related_issue="#3329",
            why="T07 첫 필드 홍길동 정본. 회사명이 fields[0].",
            fmt="hwp5",
            fields=tuple(_field01()),
            notes="목차1 이 5회. 순번 없는 키는 첫 매치만.",
        ),
        FormCatalog(
            ident="field-01-memo",
            title="누름틀 11개 + HelpState 지시문",
            family="sample",
            genre="지시문",
            sample="samples/field-01-memo.hwp",
            related_issue="#3281",
            why="guide/memo 가 fields 조사의 사람용 지시문.",
            fmt="hwp5",
            fields=tuple(
                F(rec.name, rec.guide, rec.value, memo=f"{rec.name} 기입 요령", paragraph=rec.paragraph)
                for rec in _field01()
            ),
        ),
        FormCatalog(
            ident="form-01",
            title="명령 단추 예제 문서",
            family="sample",
            genre="단건",
            sample="samples/form-01.hwp",
            related_issue="#3329",
            why="레시피 01 실측. 누름틀 myMsg01 1개.",
            fmt="hwp5",
            fields=(F("myMsg01", "여기에 입력", "", paragraph=10),),
        ),
        FormCatalog(
            ident="gian-1",
            title="일반기안문 별지 제1호서식",
            family="공문서",
            genre="기안",
            sample="tools/forms/일반기안문_서식.hwpx",
            related_issue="#3372",
            why="행정업무운영 편람 별지 제1호. 누름틀 23곳.",
            fmt="hwpx",
            fields=tuple(_gian()),
        ),
        FormCatalog(
            ident="gian-2",
            title="간이기안문 별지 제2호서식",
            family="공문서",
            genre="내부결재",
            sample="tools/forms/간이기안문_서식.hwpx",
            related_issue="#3372",
            why="결재란 표 + 누름틀 13곳. 안내문과 실값 충돌 회피(#3380).",
            fmt="hwpx",
            fields=tuple(_gani()),
        ),
        FormCatalog(
            ident="reg-80168",
            title="규제영향분석서 80168",
            family="규제",
            genre="반복 필드",
            sample="samples/80168_regulatory_analysis.hwp",
            related_issue="#3476",
            why="피규제집단명 ×14. 이름[N] 지목의 정본 서식.",
            fmt="hwp5",
            fields=tuple(_regulatory()),
        ),
        FormCatalog(
            ident="hongbo",
            title="보도자료 서식",
            family="홍보",
            genre="보도",
            sample="samples/20250130-hongbo.hwp",
            related_issue="#4781",
            why="기관명이 첫 칸. 로고 셀은 채우면 안 된다(가이드 1-4).",
            fmt="hwp5",
            fields=(
                F("기관명", "발신 기관(로고 셀이면 건너뜀)", "", paragraph=0, nested=("table:0", "r0c0")),
                F("배포일시", "배포 연월일시", "", paragraph=1),
                F("담당부서", "담당 부서", "", paragraph=2),
                F("담당자", "담당자 성명", "", paragraph=3),
                F("연락처", "담당 전화", "", paragraph=4),
                F("제목", "보도자료 제목", "", paragraph=5),
                F("부제", "부제목", "", paragraph=6),
                F("본문", "보도 본문", "", paragraph=7),
                F("문의처", "추가 문의", "", paragraph=8),
                F("첨부", "첨부 자료명", "", paragraph=9),
                F("사진설명", "사진 캡션", "", paragraph=10),
                F("홈페이지", "관련 URL", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="trip-apply",
            title="공무 출장신청서",
            family="인사",
            genre="출장",
            sample="fixtures/forms/출장신청서.hwp",
            related_issue="#3329",
            why="출장자 성명이 반복될 수 있는 여비 서식.",
            fmt="hwp5",
            fields=(
                F("소속", "소속 부서", "", paragraph=0),
                F("직급", "직급", "", paragraph=1),
                F("성명", "출장자 성명", "", paragraph=2),
                F("출장목적", "출장 목적", "", paragraph=3),
                F("출장지", "출장 목적지", "", paragraph=4),
                F("출발일", "출발 연월일", "", paragraph=5),
                F("귀임일", "귀임 연월일", "", paragraph=6),
                F("교통수단", "교통 수단", "", paragraph=7),
                F("여비구분", "국내/국외", "", paragraph=8),
                F("여비예산", "예산 과목", "", paragraph=9),
                F("동행자", "동행자", "", paragraph=10),
                F("긴급연락처", "비상 연락", "", paragraph=11),
                F("신청일", "신청 연월일", "", paragraph=12),
                F("신청자", "신청자 성명", "", paragraph=13),
            ),
        ),
        FormCatalog(
            ident="leave-apply",
            title="연가·휴가원",
            family="인사",
            genre="휴가",
            sample="fixtures/forms/휴가원.hwp",
            related_issue="#3329",
            why="휴가 종류·기간. 대리자 성명이 별도 필드.",
            fmt="hwp5",
            fields=(
                F("소속", "소속", "", paragraph=0),
                F("직급", "직급", "", paragraph=1),
                F("성명", "신청자 성명", "", paragraph=2),
                F("휴가종류", "연가/병가/공가/특별휴가", "", paragraph=3),
                F("시작일", "휴가 시작일", "", paragraph=4),
                F("종료일", "휴가 종료일", "", paragraph=5),
                F("일수", "사용 일수", "", paragraph=6),
                F("잔여연가", "잔여 연가", "", paragraph=7),
                F("사유", "휴가 사유", "", paragraph=8),
                F("업무대리자", "업무 대리자", "", paragraph=9),
                F("연락처", "휴가 중 연락처", "", paragraph=10),
                F("신청일", "신청일", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="bokhak",
            title="복학원서",
            family="학사",
            genre="원서",
            sample="fixtures/forms/복학원서.hwp",
            related_issue="#3329",
            why="레시피·report edit_demo_bokhak. 표 격자와 누름틀이 섞임.",
            fmt="hwp5",
            fields=(
                F("대학", "대학명", "", paragraph=0),
                F("학과", "학과", "", paragraph=1),
                F("학번", "학번", "", paragraph=2),
                F("성명", "학생 성명", "", paragraph=3),
                F("학년", "복학 학년", "", paragraph=4),
                F("휴학기간", "휴학 기간", "", paragraph=5),
                F("복학예정학기", "복학 학기", "", paragraph=6),
                F("휴학사유", "휴학 사유", "", paragraph=7),
                F("연락처", "휴대전화", "", paragraph=8),
                F("보호자", "보호자 성명", "", paragraph=9),
                F("보호자연락처", "보호자 전화", "", paragraph=10),
                F("주소", "현주소", "", paragraph=11),
                F("신청일", "신청일", "", paragraph=12),
            ),
        ),
        FormCatalog(
            ident="admission",
            title="입학원서",
            family="학사",
            genre="원서",
            sample="fixtures/forms/입학원서.hwp",
            related_issue="#3329",
            why="지원자 인적사항 + 보호자 반복 연락처.",
            fmt="hwp5",
            fields=(
                F("수험번호", "수험번호", "", paragraph=0),
                F("전형", "전형 유형", "", paragraph=1),
                F("모집단위", "모집 단위", "", paragraph=2),
                F("성명", "지원자 성명", "", paragraph=3),
                F("주민등록번호", "주민등록번호", "", paragraph=4),
                F("생년월일", "생년월일", "", paragraph=5),
                F("주소", "주소", "", paragraph=6),
                F("연락처", "지원자 전화", "", paragraph=7),
                F("이메일", "전자우편", "", paragraph=8),
                F("출신학교", "출신 고등학교", "", paragraph=9),
                F("졸업연월", "졸업 연월", "", paragraph=10),
                F("보호자성명", "보호자 성명", "", paragraph=11),
                F("보호자관계", "관계", "", paragraph=12),
                F("보호자연락처", "보호자 전화", "", paragraph=13),
                F("지원동기", "지원 동기", "", paragraph=14),
            ),
        ),
        FormCatalog(
            ident="scholarship",
            title="장학금 신청서",
            family="학사",
            genre="신청",
            sample="fixtures/forms/장학금신청서.hwp",
            related_issue="#3329",
            why="소득·성적 칸. 동일 이름 가족 구성원 반복.",
            fmt="hwp5",
            fields=(
                F("단과대학", "단과대학", "", paragraph=0),
                F("학과", "학과", "", paragraph=1),
                F("학번", "학번", "", paragraph=2),
                F("성명", "신청자", "", paragraph=3),
                F("학년", "학년", "", paragraph=4),
                F("평균평점", "직전학기 평점", "", paragraph=5),
                F("이수학점", "이수학점", "", paragraph=6),
                F("장학과", "신청 장학과", "", paragraph=7),
                F("신청금액", "신청 금액", "", paragraph=8),
                F("계좌은행", "은행", "", paragraph=9),
                F("계좌번호", "계좌", "", paragraph=10),
                F("예금주", "예금주", "", paragraph=11),
                *repeat("가족성명", 4, "가족 성명", start_para=12),
                *repeat("가족관계", 4, "가족 관계", start_para=16),
                F("신청사유", "신청 사유", "", paragraph=20),
            ),
        ),
        FormCatalog(
            ident="minwon",
            title="민원신청서",
            family="민원",
            genre="신청",
            sample="fixtures/forms/민원신청서.hwp",
            related_issue="#3329",
            why="신청인/대리인 성명·주소가 같은 이름으로 반복.",
            fmt="hwp5",
            fields=(
                F("민원제목", "민원 제목", "", paragraph=0),
                F("민원내용", "민원 요지", "", paragraph=1),
                F("성명", "신청인 성명", "", paragraph=2),
                F("주소", "신청인 주소", "", paragraph=3),
                F("연락처", "신청인 전화", "", paragraph=4),
                F("전자우편", "신청인 메일", "", paragraph=5),
                F("성명", "대리인 성명", "", paragraph=6),
                F("주소", "대리인 주소", "", paragraph=7),
                F("연락처", "대리인 전화", "", paragraph=8),
                F("관계", "신청인과의 관계", "", paragraph=9),
                F("처리기한", "희망 처리기한", "", paragraph=10),
                F("공개여부", "공개/비공개", "", paragraph=11),
                F("접수번호", "접수번호", "", paragraph=12),
                F("접수일", "접수일", "", paragraph=13),
            ),
        ),
        FormCatalog(
            ident="minutes",
            title="회의록",
            family="공문서",
            genre="회의",
            sample="fixtures/forms/회의록.hwp",
            related_issue="#3372",
            why="참석자 성명 반복. 후속 서식 후보(tools/forms README).",
            fmt="hwpx",
            fields=(
                F("회의명", "회의명", "", paragraph=0),
                F("개최일시", "개최 일시", "", paragraph=1),
                F("장소", "장소", "", paragraph=2),
                F("주관부서", "주관 부서", "", paragraph=3),
                *repeat("참석자", 8, "참석자 성명", start_para=4),
                F("안건1", "제1호 안건", "", paragraph=12),
                F("안건2", "제2호 안건", "", paragraph=13),
                F("안건3", "제3호 안건", "", paragraph=14),
                F("결정사항", "결정·지시", "", paragraph=15),
                F("작성자", "작성자", "", paragraph=16),
                F("확인자", "확인자", "", paragraph=17),
            ),
        ),
        FormCatalog(
            ident="sihaeng",
            title="시행문",
            family="공문서",
            genre="시행",
            sample="fixtures/forms/시행문.hwp",
            related_issue="#3372",
            why="일반기안문에서 변환되는 시행 봉투.",
            fmt="hwpx",
            fields=(
                F("행정기관명", "발신 기관", "", paragraph=0),
                F("수신자", "수신자", "", paragraph=1),
                F("제목", "시행 제목", "", paragraph=2),
                F("본문", "시행 본문", "", paragraph=3),
                F("붙임", "붙임", "", paragraph=4),
                F("발신명의", "발신명의", "", paragraph=5),
                F("시행번호", "시행번호", "", paragraph=6),
                F("시행일", "시행일", "", paragraph=7),
                F("담당자", "담당자", "", paragraph=8),
                F("전화번호", "전화", "", paragraph=9),
                F("전자우편", "메일", "", paragraph=10),
                F("공개구분", "공개구분", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="gongo",
            title="공고문",
            family="공문서",
            genre="공고",
            sample="fixtures/forms/공고문.hwp",
            related_issue="#3372",
            why="tools/forms 후속 후보. 공고 기간이 시작/종료 쌍.",
            fmt="hwpx",
            fields=(
                F("공고기관", "공고 기관", "", paragraph=0),
                F("공고번호", "공고번호", "", paragraph=1),
                F("공고제목", "공고 제목", "", paragraph=2),
                F("공고내용", "공고 본문", "", paragraph=3),
                F("시작일", "공고 시작", "", paragraph=4),
                F("종료일", "공고 종료", "", paragraph=5),
                F("제출처", "제출처", "", paragraph=6),
                F("문의처", "문의처", "", paragraph=7),
                F("담당자", "담당자", "", paragraph=8),
                F("전화번호", "전화", "", paragraph=9),
                F("게시일", "게시일", "", paragraph=10),
            ),
        ),
        FormCatalog(
            ident="labor-contract",
            title="표준 근로계약서",
            family="노무",
            genre="계약",
            sample="fixtures/forms/근로계약서.hwp",
            related_issue="#3329",
            why="사용자/근로자 성명·주소가 같은 이름.",
            fmt="hwp5",
            fields=(
                F("사업장명", "사업장", "", paragraph=0),
                F("성명", "사용자 성명", "", paragraph=1),
                F("주소", "사용자 주소", "", paragraph=2),
                F("성명", "근로자 성명", "", paragraph=3),
                F("주소", "근로자 주소", "", paragraph=4),
                F("생년월일", "근로자 생년월일", "", paragraph=5),
                F("계약시작일", "근로 시작", "", paragraph=6),
                F("계약종료일", "근로 종료", "", paragraph=7),
                F("근무장소", "근무 장소", "", paragraph=8),
                F("업무내용", "담당 업무", "", paragraph=9),
                F("소정근로시간", "소정 근로", "", paragraph=10),
                F("임금", "임금 액수", "", paragraph=11),
                F("임금지급일", "지급일", "", paragraph=12),
                F("작성일", "작성일", "", paragraph=13),
            ),
        ),
        FormCatalog(
            ident="hr-card",
            title="인사기록카드",
            family="인사",
            genre="기록",
            sample="fixtures/forms/인사기록카드.hwp",
            related_issue="#3329",
            why="학력·경력 행이 같은 이름 반복.",
            fmt="hwp5",
            fields=(
                F("사번", "사원번호", "", paragraph=0),
                F("성명", "성명", "", paragraph=1),
                F("한자성명", "한자", "", paragraph=2),
                F("생년월일", "생년월일", "", paragraph=3),
                F("직급", "직급", "", paragraph=4),
                F("직위", "직위", "", paragraph=5),
                F("소속", "소속", "", paragraph=6),
                F("입사일", "입사일", "", paragraph=7),
                *repeat("학력학교", 3, "학력 학교", start_para=8),
                *repeat("학력전공", 3, "학력 전공", start_para=11),
                *repeat("경력기관", 4, "경력 기관", start_para=14),
                F("주소", "현주소", "", paragraph=18),
                F("연락처", "전화", "", paragraph=19),
            ),
        ),
        FormCatalog(
            ident="health-survey",
            title="건강검진 문진표",
            family="보건",
            genre="문진",
            sample="fixtures/forms/건강검진문진표.hwp",
            related_issue="#3329",
            why="증상 체크와 복용약 반복 칸.",
            fmt="hwp5",
            fields=(
                F("성명", "수검자", "", paragraph=0),
                F("주민등록번호", "주민번호", "", paragraph=1),
                F("연락처", "전화", "", paragraph=2),
                F("신장", "cm", "", paragraph=3),
                F("체중", "kg", "", paragraph=4),
                F("혈압", "혈압", "", paragraph=5),
                F("흡연여부", "흡연", "", paragraph=6),
                F("음주여부", "음주", "", paragraph=7),
                *repeat("복용약", 5, "복용 중인 약", start_para=8),
                *repeat("과거병력", 3, "과거 병력", start_para=13),
                F("문진일", "문진일", "", paragraph=16),
            ),
        ),
        FormCatalog(
            ident="biz-reg",
            title="사업자등록 신청서",
            family="세무",
            genre="신청",
            sample="fixtures/forms/사업자등록신청서.hwp",
            related_issue="#3329",
            why="공동사업자 성명 반복.",
            fmt="hwp5",
            fields=(
                F("상호", "상호", "", paragraph=0),
                F("대표자", "대표자", "", paragraph=1),
                F("생년월일", "대표자 생년월일", "", paragraph=2),
                F("사업장소재지", "사업장", "", paragraph=3),
                F("업태", "업태", "", paragraph=4),
                F("종목", "종목", "", paragraph=5),
                F("개업일", "개업일", "", paragraph=6),
                F("사업자단위과세", "여부", "", paragraph=7),
                *repeat("공동사업자", 3, "공동사업자 성명", start_para=8),
                F("연락처", "전화", "", paragraph=11),
                F("전자우편", "메일", "", paragraph=12),
                F("신청일", "신청일", "", paragraph=13),
            ),
        ),
        FormCatalog(
            ident="build-permit",
            title="건축허가 신청서",
            family="인허가",
            genre="허가",
            sample="fixtures/forms/건축허가신청서.hwp",
            related_issue="#3329",
            why="건축주/설계자/시공자 성명 반복.",
            fmt="hwp5",
            fields=(
                F("허가번호", "허가번호", "", paragraph=0),
                F("대지위치", "대지 위치", "", paragraph=1),
                F("지번", "지번", "", paragraph=2),
                F("대지면적", "대지면적", "", paragraph=3),
                F("건축면적", "건축면적", "", paragraph=4),
                F("연면적", "연면적", "", paragraph=5),
                F("용도", "건축 용도", "", paragraph=6),
                F("성명", "건축주 성명", "", paragraph=7),
                F("주소", "건축주 주소", "", paragraph=8),
                F("성명", "설계자 성명", "", paragraph=9),
                F("자격번호", "설계 자격", "", paragraph=10),
                F("성명", "시공자 성명", "", paragraph=11),
                F("등록번호", "건설업 등록", "", paragraph=12),
                F("착공예정일", "착공", "", paragraph=13),
                F("준공예정일", "준공", "", paragraph=14),
            ),
        ),
        FormCatalog(
            ident="eia",
            title="환경영향평가서 표지",
            family="환경",
            genre="평가",
            sample="fixtures/forms/환경영향평가서.hwp",
            related_issue="#3476",
            why="평가 항목명이 반복되는 표지+총괄.",
            fmt="hwp5",
            fields=(
                F("사업명", "사업명", "", paragraph=0),
                F("사업자", "사업자", "", paragraph=1),
                F("평가대행자", "평가 대행", "", paragraph=2),
                F("사업위치", "위치", "", paragraph=3),
                F("사업기간", "기간", "", paragraph=4),
                *repeat("평가항목", 6, "평가 항목", start_para=5),
                F("협의기관", "협의 기관", "", paragraph=11),
                F("작성일", "작성일", "", paragraph=12),
            ),
        ),
        FormCatalog(
            ident="research-plan",
            title="연구계획서",
            family="연구",
            genre="계획",
            sample="fixtures/forms/연구계획서.hwp",
            related_issue="#3476",
            why="공동연구원 성명 반복. 사업계획서 계열.",
            fmt="hwp5",
            fields=(
                F("과제명", "과제명", "", paragraph=0),
                F("연구책임자", "연구책임자", "", paragraph=1),
                F("소속기관", "주관 기관", "", paragraph=2),
                F("연구기간", "연구 기간", "", paragraph=3),
                F("연구비", "연구비", "", paragraph=4),
                *repeat("공동연구원", 5, "공동연구원", start_para=5),
                F("연구목표", "목표", "", paragraph=10),
                F("연구내용", "내용", "", paragraph=11),
                F("기대효과", "기대효과", "", paragraph=12),
                F("키워드", "한글 키워드", "", paragraph=13),
            ),
        ),
        FormCatalog(
            ident="eval-sheet",
            title="평가표",
            family="평가",
            genre="채점",
            sample="fixtures/forms/평가표.hwp",
            related_issue="#3476",
            why="평가항목·배점·점수가 행마다 같은 이름.",
            fmt="hwp5",
            fields=(
                F("평가회차", "회차", "", paragraph=0),
                F("평가대상", "대상", "", paragraph=1),
                F("평가자", "평가자", "", paragraph=2),
                *repeat("평가항목", 8, "평가 항목", start_para=3),
                *repeat("배점", 8, "배점", start_para=11),
                *repeat("점수", 8, "점수", start_para=19),
                F("총점", "총점", "", paragraph=27),
                F("종합의견", "의견", "", paragraph=28),
            ),
        ),
        FormCatalog(
            ident="bid",
            title="입찰참가신청서",
            family="계약",
            genre="입찰",
            sample="fixtures/forms/입찰참가신청서.hwp",
            related_issue="#3329",
            why="대표자/대리인 성명 반복.",
            fmt="hwp5",
            fields=(
                F("공고번호", "입찰 공고번호", "", paragraph=0),
                F("입찰건명", "건명", "", paragraph=1),
                F("상호", "상호", "", paragraph=2),
                F("사업자번호", "사업자등록번호", "", paragraph=3),
                F("성명", "대표자", "", paragraph=4),
                F("주소", "본점 주소", "", paragraph=5),
                F("성명", "대리인", "", paragraph=6),
                F("위임범위", "위임 범위", "", paragraph=7),
                F("연락처", "전화", "", paragraph=8),
                F("전자우편", "메일", "", paragraph=9),
                F("입찰보증금", "보증금", "", paragraph=10),
                F("신청일", "신청일", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="spend",
            title="지출결의서",
            family="회계",
            genre="결의",
            sample="fixtures/forms/지출결의서.hwp",
            related_issue="#3329",
            why="계정과목·적요가 여러 줄 같은 이름.",
            fmt="hwp5",
            fields=(
                F("결의번호", "결의번호", "", paragraph=0),
                F("결의일", "결의일", "", paragraph=1),
                F("지급처", "지급처", "", paragraph=2),
                *repeat("계정과목", 4, "계정과목", start_para=3),
                *repeat("적요", 4, "적요", start_para=7),
                *repeat("금액", 4, "금액", start_para=11),
                F("합계", "합계", "", paragraph=15),
                F("원인행위자", "원인행위", "", paragraph=16),
                F("검인자", "검인", "", paragraph=17),
                F("지출관", "지출관", "", paragraph=18),
            ),
        ),
        FormCatalog(
            ident="pumui",
            title="품의서",
            family="공문서",
            genre="품의",
            sample="fixtures/forms/품의서.hwp",
            related_issue="#3372",
            why="내부 품의. 검토자 직위가 반복.",
            fmt="hwpx",
            fields=(
                F("품의번호", "품의번호", "", paragraph=0),
                F("제목", "품의 제목", "", paragraph=1),
                F("기안자", "기안자", "", paragraph=2),
                F("기안부서", "기안 부서", "", paragraph=3),
                *repeat("검토자", 3, "검토자", start_para=4),
                F("결재권자", "결재권자", "", paragraph=7),
                F("품의내용", "내용", "", paragraph=8),
                F("소요예산", "예산", "", paragraph=9),
                F("관련근거", "근거", "", paragraph=10),
                F("기안일", "기안일", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="hyopjo",
            title="협조전",
            family="공문서",
            genre="협조",
            sample="fixtures/forms/협조전.hwp",
            related_issue="#3372",
            why="수신 부서가 여러 칸 같은 이름.",
            fmt="hwpx",
            fields=(
                F("발신부서", "발신 부서", "", paragraph=0),
                *repeat("수신부서", 4, "수신 부서", start_para=1),
                F("제목", "협조 제목", "", paragraph=5),
                F("협조내용", "내용", "", paragraph=6),
                F("회신기한", "회신 기한", "", paragraph=7),
                F("담당자", "담당자", "", paragraph=8),
                F("연락처", "전화", "", paragraph=9),
                F("시행일", "시행일", "", paragraph=10),
            ),
        ),
        FormCatalog(
            ident="inspect",
            title="검수조서",
            family="계약",
            genre="검수",
            sample="fixtures/forms/검수조서.hwp",
            related_issue="#3329",
            why="품목·규격·수량이 행 반복.",
            fmt="hwp5",
            fields=(
                F("계약명", "계약명", "", paragraph=0),
                F("계약번호", "계약번호", "", paragraph=1),
                F("계약상대자", "상대자", "", paragraph=2),
                *repeat("품목", 5, "품목", start_para=3),
                *repeat("규격", 5, "규격", start_para=8),
                *repeat("수량", 5, "수량", start_para=13),
                F("검수일", "검수일", "", paragraph=18),
                F("검수자", "검수자", "", paragraph=19),
                F("입회자", "입회자", "", paragraph=20),
                F("판정", "합격/불합격", "", paragraph=21),
            ),
        ),
        FormCatalog(
            ident="pass-apply",
            title="출입증 신청서",
            family="보안",
            genre="출입",
            sample="fixtures/forms/출입증신청서.hwp",
            related_issue="#3329",
            why="방문 동반자 성명 반복.",
            fmt="hwp5",
            fields=(
                F("신청구분", "신규/재발급", "", paragraph=0),
                F("성명", "신청자", "", paragraph=1),
                F("소속", "소속", "", paragraph=2),
                F("직위", "직위", "", paragraph=3),
                F("생년월일", "생년월일", "", paragraph=4),
                F("연락처", "전화", "", paragraph=5),
                F("출입구역", "출입 구역", "", paragraph=6),
                F("유효기간", "유효 기간", "", paragraph=7),
                *repeat("동반자", 3, "동반자 성명", start_para=8),
                F("신청사유", "사유", "", paragraph=11),
                F("신청일", "신청일", "", paragraph=12),
            ),
        ),
        FormCatalog(
            ident="foi",
            title="정보공개 청구서",
            family="민원",
            genre="공개청구",
            sample="fixtures/forms/정보공개청구서.hwp",
            related_issue="#3329",
            why="청구인/대리인 인적사항 반복.",
            fmt="hwp5",
            fields=(
                F("청구기관", "청구 대상기관", "", paragraph=0),
                F("정보내용", "청구 정보", "", paragraph=1),
                F("공개방법", "열람/사본/전자파일", "", paragraph=2),
                F("수령방법", "직접/우편/전자", "", paragraph=3),
                F("성명", "청구인", "", paragraph=4),
                F("주소", "청구인 주소", "", paragraph=5),
                F("연락처", "청구인 전화", "", paragraph=6),
                F("성명", "대리인", "", paragraph=7),
                F("주소", "대리인 주소", "", paragraph=8),
                F("위임여부", "위임 여부", "", paragraph=9),
                F("청구일", "청구일", "", paragraph=10),
            ),
        ),
        FormCatalog(
            ident="pii-access",
            title="개인정보 열람 청구서",
            family="민원",
            genre="개인정보",
            sample="fixtures/forms/개인정보열람청구서.hwp",
            related_issue="#3329",
            why="정보주체/법정대리인 성명 반복.",
            fmt="hwp5",
            fields=(
                F("처리기관", "처리 기관", "", paragraph=0),
                F("청구내용", "열람/정정/삭제/정지", "", paragraph=1),
                F("성명", "정보주체", "", paragraph=2),
                F("생년월일", "정보주체 생년월일", "", paragraph=3),
                F("주소", "정보주체 주소", "", paragraph=4),
                F("성명", "법정대리인", "", paragraph=5),
                F("관계", "관계", "", paragraph=6),
                F("연락처", "연락처", "", paragraph=7),
                F("열람방법", "열람 방법", "", paragraph=8),
                F("청구일", "청구일", "", paragraph=9),
            ),
        ),
        FormCatalog(
            ident="car-log",
            title="차량 운행일지",
            family="총무",
            genre="일지",
            sample="fixtures/forms/차량운행일지.hwp",
            related_issue="#3476",
            why="운행 행마다 출발/도착/운전자 반복.",
            fmt="hwp5",
            fields=(
                F("차량번호", "차량번호", "", paragraph=0),
                F("차종", "차종", "", paragraph=1),
                F("운행월", "운행 연월", "", paragraph=2),
                *repeat("운전자", 6, "운전자", start_para=3),
                *repeat("출발지", 6, "출발지", start_para=9),
                *repeat("도착지", 6, "도착지", start_para=15),
                *repeat("주행거리", 6, "주행거리", start_para=21),
                F("연료량", "주유", "", paragraph=27),
                F("확인자", "확인자", "", paragraph=28),
            ),
        ),
        FormCatalog(
            ident="overtime",
            title="초과근무 신청서",
            family="인사",
            genre="초과근무",
            sample="fixtures/forms/초과근무신청서.hwp",
            related_issue="#3329",
            why="근무 일자·시간이 여러 날 반복.",
            fmt="hwp5",
            fields=(
                F("소속", "소속", "", paragraph=0),
                F("직급", "직급", "", paragraph=1),
                F("성명", "신청자", "", paragraph=2),
                *repeat("근무일", 5, "근무일", start_para=3),
                *repeat("시작시각", 5, "시작", start_para=8),
                *repeat("종료시각", 5, "종료", start_para=13),
                F("업무내용", "업무", "", paragraph=18),
                F("신청일", "신청일", "", paragraph=19),
                F("승인자", "승인자", "", paragraph=20),
            ),
        ),
        FormCatalog(
            ident="training",
            title="교육훈련 신청서",
            family="인사",
            genre="교육",
            sample="fixtures/forms/교육훈련신청서.hwp",
            related_issue="#3329",
            why="교육과정명 단건 + 동행 교육생 반복.",
            fmt="hwp5",
            fields=(
                F("과정명", "교육 과정", "", paragraph=0),
                F("주관기관", "주관", "", paragraph=1),
                F("교육장소", "장소", "", paragraph=2),
                F("교육기간", "기간", "", paragraph=3),
                F("교육비", "교육비", "", paragraph=4),
                F("성명", "신청자", "", paragraph=5),
                F("직급", "직급", "", paragraph=6),
                F("소속", "소속", "", paragraph=7),
                *repeat("교육생", 4, "동행 교육생", start_para=8),
                F("신청사유", "사유", "", paragraph=12),
                F("신청일", "신청일", "", paragraph=13),
            ),
        ),
        FormCatalog(
            ident="proposal-cover",
            title="제안서 표지",
            family="제안",
            genre="표지",
            sample="fixtures/forms/제안서표지.hwp",
            related_issue="#3329",
            why="제안사/공동수급 구성원 상호 반복.",
            fmt="hwp5",
            fields=(
                F("사업명", "사업명", "", paragraph=0),
                F("발주기관", "발주 기관", "", paragraph=1),
                F("제안사", "주관사", "", paragraph=2),
                *repeat("구성원", 4, "공동수급 구성원", start_para=3),
                F("대표자", "대표자", "", paragraph=7),
                F("제출일", "제출일", "", paragraph=8),
                F("유효기간", "제안 유효", "", paragraph=9),
                F("연락처", "담당 전화", "", paragraph=10),
                F("담당자", "담당자", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="security-oath",
            title="보안서약서",
            family="보안",
            genre="서약",
            sample="fixtures/forms/보안서약서.hwp",
            related_issue="#3329",
            why="서약자 단건. 첫 필드만 홍길동 넣는 T07 변형.",
            fmt="hwp5",
            fields=(
                F("성명", "서약자", "", paragraph=0),
                F("소속", "소속", "", paragraph=1),
                F("직위", "직위", "", paragraph=2),
                F("생년월일", "생년월일", "", paragraph=3),
                F("서약일", "서약일", "", paragraph=4),
                F("서약내용", "서약 본문", "", paragraph=5),
                F("입회자", "입회자", "", paragraph=6),
            ),
        ),
        FormCatalog(
            ident="asset-out",
            title="자산 반출 신청서",
            family="총무",
            genre="반출",
            sample="fixtures/forms/자산반출신청서.hwp",
            related_issue="#3476",
            why="반출 물품명·수량 반복.",
            fmt="hwp5",
            fields=(
                F("신청부서", "신청 부서", "", paragraph=0),
                F("신청자", "신청자", "", paragraph=1),
                *repeat("물품명", 5, "물품명", start_para=2),
                *repeat("수량", 5, "수량", start_para=7),
                F("반출목적", "목적", "", paragraph=12),
                F("반출일", "반출일", "", paragraph=13),
                F("반입예정일", "반입 예정", "", paragraph=14),
                F("반출지", "반출 장소", "", paragraph=15),
                F("승인자", "승인자", "", paragraph=16),
            ),
        ),
        FormCatalog(
            ident="room-book",
            title="회의실 사용 신청서",
            family="총무",
            genre="예약",
            sample="fixtures/forms/회의실사용신청서.hwp",
            related_issue="#3329",
            why="사용 일시가 여러 슬롯 반복.",
            fmt="hwp5",
            fields=(
                F("회의실", "회의실명", "", paragraph=0),
                F("사용목적", "목적", "", paragraph=1),
                F("신청부서", "부서", "", paragraph=2),
                F("신청자", "신청자", "", paragraph=3),
                F("연락처", "전화", "", paragraph=4),
                F("참석인원", "인원", "", paragraph=5),
                *repeat("사용일", 3, "사용일", start_para=6),
                *repeat("시작시각", 3, "시작", start_para=9),
                *repeat("종료시각", 3, "종료", start_para=12),
                F("기자재", "기자재", "", paragraph=15),
            ),
        ),
        FormCatalog(
            ident="trip-settle",
            title="출장여비 정산서",
            family="회계",
            genre="정산",
            sample="fixtures/forms/출장여비정산서.hwp",
            related_issue="#3476",
            why="일자별 교통·숙박·식비 반복.",
            fmt="hwp5",
            fields=(
                F("출장자", "출장자", "", paragraph=0),
                F("소속", "소속", "", paragraph=1),
                F("출장지", "출장지", "", paragraph=2),
                *repeat("일자", 5, "일자", start_para=3),
                *repeat("교통비", 5, "교통비", start_para=8),
                *repeat("숙박비", 5, "숙박비", start_para=13),
                *repeat("식비", 5, "식비", start_para=18),
                F("합계", "합계", "", paragraph=23),
                F("정산일", "정산일", "", paragraph=24),
            ),
        ),
        FormCatalog(
            ident="purchase",
            title="구매 요구서",
            family="총무",
            genre="구매",
            sample="fixtures/forms/구매요구서.hwp",
            related_issue="#3476",
            why="요구 품목 행 반복.",
            fmt="hwp5",
            fields=(
                F("요구부서", "요구 부서", "", paragraph=0),
                F("요구자", "요구자", "", paragraph=1),
                F("사용목적", "목적", "", paragraph=2),
                *repeat("품명", 6, "품명", start_para=3),
                *repeat("규격", 6, "규격", start_para=9),
                *repeat("수량", 6, "수량", start_para=15),
                *repeat("추정단가", 6, "단가", start_para=21),
                F("희망납기", "납기", "", paragraph=27),
                F("예산과목", "예산", "", paragraph=28),
            ),
        ),
        FormCatalog(
            ident="disposal",
            title="불용품 폐기 신청서",
            family="총무",
            genre="폐기",
            sample="fixtures/forms/폐기업무신청서.hwp",
            related_issue="#3476",
            why="폐기 물품 목록 반복.",
            fmt="hwp5",
            fields=(
                F("신청부서", "부서", "", paragraph=0),
                F("신청자", "신청자", "", paragraph=1),
                *repeat("물품명", 6, "물품명", start_para=2),
                *repeat("취득일", 6, "취득일", start_para=8),
                *repeat("장부가액", 6, "장부가액", start_para=14),
                F("폐기사유", "사유", "", paragraph=20),
                F("처분방법", "폐기/매각", "", paragraph=21),
                F("신청일", "신청일", "", paragraph=22),
            ),
        ),
        FormCatalog(
            ident="transfer-list",
            title="문서 이관 목록",
            family="기록",
            genre="이관",
            sample="fixtures/forms/문서이관목록.hwp",
            related_issue="#3476",
            why="철 제목·생산연도가 행 반복.",
            fmt="hwp5",
            fields=(
                F("이관연도", "이관 연도", "", paragraph=0),
                F("이관부서", "이관 부서", "", paragraph=1),
                F("인계자", "인계자", "", paragraph=2),
                F("인수자", "인수자", "", paragraph=3),
                *repeat("철제목", 8, "철 제목", start_para=4),
                *repeat("생산연도", 8, "생산연도", start_para=12),
                *repeat("보존기간", 8, "보존기간", start_para=20),
                F("이관일", "이관일", "", paragraph=28),
            ),
        ),
        FormCatalog(
            ident="record-eval",
            title="기록물 평가서",
            family="기록",
            genre="평가",
            sample="fixtures/forms/기록물평가서.hwp",
            related_issue="#3476",
            why="평가 대상 철이 같은 이름 반복.",
            fmt="hwp5",
            fields=(
                F("평가위원회", "위원회", "", paragraph=0),
                F("평가일", "평가일", "", paragraph=1),
                *repeat("대상기록", 6, "대상 기록", start_para=2),
                *repeat("평가의견", 6, "평가 의견", start_para=8),
                *repeat("처분", 6, "보존/폐기", start_para=14),
                F("위원장", "위원장", "", paragraph=20),
                F("간사", "간사", "", paragraph=21),
            ),
        ),
        FormCatalog(
            ident="admin-appeal",
            title="행정심판 청구서",
            family="쟁송",
            genre="심판",
            sample="fixtures/forms/행정심판청구서.hwp",
            related_issue="#3329",
            why="청구인/대리인 반복 이름.",
            fmt="hwp5",
            fields=(
                F("피청구인", "피청구인", "", paragraph=0),
                F("처분내용", "처분", "", paragraph=1),
                F("처분일", "처분일", "", paragraph=2),
                F("청구취지", "취지", "", paragraph=3),
                F("청구이유", "이유", "", paragraph=4),
                F("성명", "청구인", "", paragraph=5),
                F("주소", "청구인 주소", "", paragraph=6),
                F("성명", "대리인", "", paragraph=7),
                F("주소", "대리인 주소", "", paragraph=8),
                F("연락처", "전화", "", paragraph=9),
                F("청구일", "청구일", "", paragraph=10),
            ),
        ),
        FormCatalog(
            ident="objection",
            title="이의신청서",
            family="민원",
            genre="이의",
            sample="fixtures/forms/이의신청서.hwp",
            related_issue="#3329",
            why="원처분 번호 + 신청인 단건.",
            fmt="hwp5",
            fields=(
                F("원처분기관", "처분 기관", "", paragraph=0),
                F("원처분번호", "처분 번호", "", paragraph=1),
                F("원처분일", "처분일", "", paragraph=2),
                F("이의내용", "이의 요지", "", paragraph=3),
                F("성명", "신청인", "", paragraph=4),
                F("주소", "주소", "", paragraph=5),
                F("연락처", "전화", "", paragraph=6),
                F("전자우편", "메일", "", paragraph=7),
                F("신청일", "신청일", "", paragraph=8),
            ),
        ),
        FormCatalog(
            ident="petition",
            title="청원서",
            family="민원",
            genre="청원",
            sample="fixtures/forms/청원서.hwp",
            related_issue="#3329",
            why="청원인 대표 + 연명 성명 반복.",
            fmt="hwp5",
            fields=(
                F("청원제목", "제목", "", paragraph=0),
                F("청원요지", "요지", "", paragraph=1),
                F("성명", "대표 청원인", "", paragraph=2),
                F("주소", "대표 주소", "", paragraph=3),
                *repeat("연명자", 6, "연명자 성명", start_para=4),
                F("제출기관", "제출 기관", "", paragraph=10),
                F("제출일", "제출일", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="sinmungo",
            title="국민신문고 민원",
            family="민원",
            genre="신문고",
            sample="fixtures/forms/신문고민원.hwp",
            related_issue="#3329",
            why="신청인 단건. 처리 기관 지정.",
            fmt="hwp5",
            fields=(
                F("민원제목", "제목", "", paragraph=0),
                F("민원내용", "내용", "", paragraph=1),
                F("처리기관", "희망 처리기관", "", paragraph=2),
                F("성명", "신청인", "", paragraph=3),
                F("생년월일", "생년월일", "", paragraph=4),
                F("연락처", "전화", "", paragraph=5),
                F("전자우편", "메일", "", paragraph=6),
                F("주소", "주소", "", paragraph=7),
                F("공개여부", "공개여부", "", paragraph=8),
                F("신청일", "신청일", "", paragraph=9),
            ),
        ),
        FormCatalog(
            ident="contract",
            title="물품구매 계약서",
            family="계약",
            genre="계약",
            sample="fixtures/forms/물품구매계약서.hwp",
            related_issue="#3329",
            why="발주자/계약상대자 성명·주소 반복.",
            fmt="hwp5",
            fields=(
                F("계약명", "계약명", "", paragraph=0),
                F("계약번호", "계약번호", "", paragraph=1),
                F("계약금액", "계약금액", "", paragraph=2),
                F("성명", "발주자", "", paragraph=3),
                F("주소", "발주자 주소", "", paragraph=4),
                F("성명", "계약상대자", "", paragraph=5),
                F("주소", "상대자 주소", "", paragraph=6),
                F("사업자번호", "상대자 사업자번호", "", paragraph=7),
                F("납품기한", "납품 기한", "", paragraph=8),
                F("납품장소", "납품 장소", "", paragraph=9),
                F("특약", "특약", "", paragraph=10),
                F("계약일", "계약일", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="tax-invoice",
            title="세금계산서 발행 요청",
            family="세무",
            genre="세금계산서",
            sample="fixtures/forms/세금계산서발행요청.hwp",
            related_issue="#3329",
            why="공급자/공급받는 자 등록번호 쌍.",
            fmt="hwp5",
            fields=(
                F("공급자상호", "공급자", "", paragraph=0),
                F("공급자등록번호", "공급자 등록", "", paragraph=1),
                F("공급받는자상호", "공급받는 자", "", paragraph=2),
                F("공급받는자등록번호", "공급받는 자 등록", "", paragraph=3),
                F("작성일자", "작성일", "", paragraph=4),
                F("공급가액", "공급가액", "", paragraph=5),
                F("세액", "세액", "", paragraph=6),
                F("합계", "합계", "", paragraph=7),
                *repeat("품목", 3, "품목", start_para=8),
                F("비고", "비고", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="trip-order",
            title="출장명령서",
            family="인사",
            genre="명령",
            sample="fixtures/forms/출장명령서.hwp",
            related_issue="#3329",
            why="출장자 여러 명 같은 이름.",
            fmt="hwp5",
            fields=(
                F("명령번호", "명령번호", "", paragraph=0),
                F("출장목적", "목적", "", paragraph=1),
                F("출장지", "출장지", "", paragraph=2),
                F("기간", "기간", "", paragraph=3),
                *repeat("출장자", 4, "출장자", start_para=4),
                F("여비", "여비 구분", "", paragraph=8),
                F("발령권자", "발령권자", "", paragraph=9),
                F("발령일", "발령일", "", paragraph=10),
            ),
        ),
        FormCatalog(
            ident="annual-leave",
            title="연가 사용 신청서",
            family="인사",
            genre="연가",
            sample="fixtures/forms/연가신청서.hwp",
            related_issue="#3329",
            why="휴가원과 다른 축 — 연가 일수 전용.",
            fmt="hwp5",
            fields=(
                F("소속", "소속", "", paragraph=0),
                F("직급", "직급", "", paragraph=1),
                F("성명", "신청자", "", paragraph=2),
                F("발생연가", "발생", "", paragraph=3),
                F("사용연가", "기사용", "", paragraph=4),
                F("잔여연가", "잔여", "", paragraph=5),
                F("신청일수", "신청 일수", "", paragraph=6),
                F("시작일", "시작", "", paragraph=7),
                F("종료일", "종료", "", paragraph=8),
                F("업무대리자", "대리자", "", paragraph=9),
                F("신청일", "신청일", "", paragraph=10),
            ),
        ),
        FormCatalog(
            ident="parental-leave",
            title="육아휴직 신청서",
            family="인사",
            genre="휴직",
            sample="fixtures/forms/육아휴직신청서.hwp",
            related_issue="#3329",
            why="자녀 성명 반복(다자녀).",
            fmt="hwp5",
            fields=(
                F("소속", "소속", "", paragraph=0),
                F("직급", "직급", "", paragraph=1),
                F("성명", "신청자", "", paragraph=2),
                *repeat("자녀성명", 3, "자녀 성명", start_para=3),
                *repeat("자녀생년월일", 3, "자녀 생년월일", start_para=6),
                F("휴직시작일", "시작", "", paragraph=9),
                F("휴직종료일", "종료", "", paragraph=10),
                F("급여계좌", "계좌", "", paragraph=11),
                F("신청일", "신청일", "", paragraph=12),
            ),
        ),
        FormCatalog(
            ident="side-job",
            title="겸직 허가 신청서",
            family="인사",
            genre="겸직",
            sample="fixtures/forms/겸직허가신청서.hwp",
            related_issue="#3329",
            why="겸직 기관이 여러 곳일 때 반복.",
            fmt="hwp5",
            fields=(
                F("소속", "소속", "", paragraph=0),
                F("직급", "직급", "", paragraph=1),
                F("성명", "신청자", "", paragraph=2),
                *repeat("겸직기관", 3, "겸직 기관", start_para=3),
                *repeat("겸직업무", 3, "겸직 업무", start_para=6),
                F("겸직기간", "기간", "", paragraph=9),
                F("겸직사유", "사유", "", paragraph=10),
                F("신청일", "신청일", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="pension",
            title="퇴직연금 청구서",
            family="연금",
            genre="청구",
            sample="fixtures/forms/퇴직연금청구서.hwp",
            related_issue="#3329",
            why="청구인/유족 성명 반복 가능.",
            fmt="hwp5",
            fields=(
                F("청구구분", "본인/유족", "", paragraph=0),
                F("성명", "청구인", "", paragraph=1),
                F("주민등록번호", "주민번호", "", paragraph=2),
                F("주소", "주소", "", paragraph=3),
                F("연락처", "전화", "", paragraph=4),
                F("퇴직일", "퇴직일", "", paragraph=5),
                F("재직기간", "재직 기간", "", paragraph=6),
                F("성명", "유족", "", paragraph=7),
                F("관계", "관계", "", paragraph=8),
                F("계좌은행", "은행", "", paragraph=9),
                F("계좌번호", "계좌", "", paragraph=10),
                F("청구일", "청구일", "", paragraph=11),
            ),
        ),
        FormCatalog(
            ident="payroll-account",
            title="급여 계좌 변경 신청",
            family="급여",
            genre="계좌",
            sample="fixtures/forms/급여계좌변경.hwp",
            related_issue="#3329",
            why="단건. 이름 필드가 첫 칸 — T07 변형.",
            fmt="hwp5",
            fields=(
                F("성명", "신청자", "", paragraph=0),
                F("사번", "사번", "", paragraph=1),
                F("소속", "소속", "", paragraph=2),
                F("기존은행", "기존 은행", "", paragraph=3),
                F("기존계좌", "기존 계좌", "", paragraph=4),
                F("변경은행", "변경 은행", "", paragraph=5),
                F("변경계좌", "변경 계좌", "", paragraph=6),
                F("예금주", "예금주", "", paragraph=7),
                F("변경사유", "사유", "", paragraph=8),
                F("신청일", "신청일", "", paragraph=9),
            ),
        ),
        FormCatalog(
            ident="family-cert",
            title="가족관계증명 청구",
            family="민원",
            genre="증명",
            sample="fixtures/forms/가족관계증명청구.hwp",
            related_issue="#3329",
            why="대상자/청구인 성명 반복.",
            fmt="hwp5",
            fields=(
                F("증명종류", "가족관계/기본/혼인/입양", "", paragraph=0),
                F("성명", "대상자", "", paragraph=1),
                F("주민등록번호", "대상자 주민번호", "", paragraph=2),
                F("성명", "청구인", "", paragraph=3),
                F("관계", "관계", "", paragraph=4),
                F("용도", "용도", "", paragraph=5),
                F("제출처", "제출처", "", paragraph=6),
                F("부수", "부수", "", paragraph=7),
                F("수령방법", "수령", "", paragraph=8),
                F("청구일", "청구일", "", paragraph=9),
            ),
        ),
        FormCatalog(
            ident="rrn-correct",
            title="주민등록 정정 신청",
            family="민원",
            genre="정정",
            sample="fixtures/forms/주민등록정정.hwp",
            related_issue="#3329",
            why="정정 전/후 값이 같은 이름 쌍이 아님 — 별도 필드.",
            fmt="hwp5",
            fields=(
                F("성명", "신청인", "", paragraph=0),
                F("주민등록번호", "주민번호", "", paragraph=1),
                F("주소", "주소", "", paragraph=2),
                F("정정항목", "항목", "", paragraph=3),
                F("정정전", "정정 전", "", paragraph=4),
                F("정정후", "정정 후", "", paragraph=5),
                F("사유", "사유", "", paragraph=6),
                F("첨부", "첨부", "", paragraph=7),
                F("신청일", "신청일", "", paragraph=8),
            ),
        ),
        FormCatalog(
            ident="building-ledger",
            title="건축물대장 열람 신청",
            family="민원",
            genre="열람",
            sample="fixtures/forms/건축물대장열람.hwp",
            related_issue="#3329",
            why="대상 건축물이 여러 동이면 소재지 반복.",
            fmt="hwp5",
            fields=(
                F("신청인", "신청인", "", paragraph=0),
                F("연락처", "전화", "", paragraph=1),
                *repeat("소재지", 3, "건축물 소재지", start_para=2),
                F("열람종류", "일반/표제부/전유부", "", paragraph=5),
                F("부수", "부수", "", paragraph=6),
                F("용도", "용도", "", paragraph=7),
                F("신청일", "신청일", "", paragraph=8),
            ),
        ),
        FormCatalog(
            ident="land-use",
            title="토지이용계획 확인 신청",
            family="민원",
            genre="확인",
            sample="fixtures/forms/토지이용계획확인.hwp",
            related_issue="#3329",
            why="여러 필지 지번 반복.",
            fmt="hwp5",
            fields=(
                F("신청인", "신청인", "", paragraph=0),
                F("연락처", "전화", "", paragraph=1),
                F("주소", "신청인 주소", "", paragraph=2),
                *repeat("지번", 4, "토지 지번", start_para=3),
                F("용도", "확인 용도", "", paragraph=7),
                F("수령방법", "수령", "", paragraph=8),
                F("신청일", "신청일", "", paragraph=9),
            ),
        ),
        FormCatalog(
            ident="empty-none",
            title="누름틀 없는 일반 문서",
            family="sample",
            genre="빈 목록",
            sample="samples/hwp3-sample.hwp",
            related_issue="#3281",
            why="fieldCount 0 은 오류가 아니라 축 전환 신호.",
            fmt="hwp5",
            fields=(),
            notes="fill-fields 축이 아님. set-cell 로 전환.",
        ),
    ]
    return tuple(forms)


def form_by_id(ident: str) -> FormCatalog:
    for form in FORMS():
        if form.ident == ident:
            return form
    raise KeyError(ident)
