#!/usr/bin/env node

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { canonicalJson, sha256Text } from './font_rule_ledger.mjs';
import { validateRegistryV2 } from './font_rule_registry_v2.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const GENERATOR_PATH = fileURLToPath(import.meta.url);
const REGISTRY_PATH = path.join(ROOT, 'assets', 'font-rules', 'font_rule_registry_v2.json');
const MANIFEST_PATH = path.join(
  ROOT,
  'assets',
  'font-rules',
  'font_rule_projection_manifest.json',
);
const MANIFEST_SCHEMA_PATH = path.join(
  ROOT,
  'assets',
  'font-rules',
  'font_rule_projection_manifest.schema.json',
);

export const GENERATED_SENTINEL = '// @generated by scripts/font_rule_projection_gen.mjs from assets/font-rules/font_rule_registry_v2.json; DO NOT EDIT.';
const LEGACY_GENERATED_SENTINEL = '// @generated by scripts/font_rule_projection_gen.mjs from assets/font-rules/font_rule_registry.json; DO NOT EDIT.';

export const OUTPUT_CONFIGS = Object.freeze([
  Object.freeze({
    projectionId: 'rust-layout-name',
    language: 'rust',
    path: 'src/renderer/font_rule_projections/layout_name.rs',
    constantStem: 'FONT_RULE_LAYOUT_NAME',
  }),
  Object.freeze({
    projectionId: 'rust-layout-metric',
    language: 'rust',
    path: 'src/renderer/font_rule_projections/layout_metric.rs',
    constantStem: 'FONT_RULE_LAYOUT_METRIC',
  }),
  Object.freeze({
    projectionId: 'canvas2d-paint',
    language: 'typescript',
    path: 'rhwp-studio/src/core/generated/font-rule-projections/canvas2d-paint.ts',
    constantStem: 'FONT_RULE_CANVAS2D_PAINT',
  }),
  Object.freeze({
    projectionId: 'canvas2d-webfont',
    language: 'typescript',
    path: 'rhwp-studio/src/core/generated/font-rule-projections/webfont-supply.ts',
    constantStem: 'FONT_RULE_CANVAS2D_WEBFONT',
  }),
  Object.freeze({
    projectionId: 'canvaskit-sfnt',
    language: 'typescript',
    path: 'rhwp-studio/src/core/generated/font-rule-projections/canvaskit-sfnt.ts',
    constantStem: 'FONT_RULE_CANVASKIT_SFNT',
  }),
]);

let stagedSequence = 0;

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function sha256Bytes(value) {
  return crypto.createHash('sha256').update(value).digest('hex');
}

function sha256File(file) {
  return sha256Bytes(fs.readFileSync(file));
}

function relativePath(file, root = ROOT) {
  return path.relative(root, file).split(path.sep).join('/');
}

function pathDigest(file, root = ROOT) {
  return { path: relativePath(file, root), sha256: sha256File(file) };
}

function projectionRow(rule) {
  const row = {
    ruleId: rule.ruleId,
    sourceBoundaryId: rule.sourceBoundaryId,
    relationType: rule.relationType,
    decisionPlane: rule.decisionPlane,
    sourceFace: rule.sourceFace,
    targetFaceOrPolicy: rule.targetFaceOrPolicy,
    conditions: rule.conditions,
    order: rule.order,
    mode: rule.projections[0].mode,
    metricEntryIds: rule.metricEntryIds,
    supply: rule.supply,
  };
  return row;
}

function rustString(value) {
  return JSON.stringify(value).replaceAll('\u2028', '\\u{2028}').replaceAll('\u2029', '\\u{2029}');
}

function rustOptionString(value) {
  return value === null || value === undefined
    ? 'None'
    : `Some(${rustString(value)})`;
}

function rustOptionInteger(value) {
  return value === null || value === undefined ? 'None' : `Some(${value})`;
}

function rustMetricEntryLines(values) {
  if (values.length === 0) return ['        metric_entry_ids: &[],'];
  if (values.length === 1) {
    return [`        metric_entry_ids: &[${rustString(values[0])}],`];
  }
  return [
    '        metric_entry_ids: &[',
    ...values.map(value => `            ${rustString(value)},`),
    '        ],',
  ];
}

function renderRustLookup(config, rows) {
  if (config.projectionId === 'rust-layout-name') {
    const arms = rows.map((row, index) => {
      const condition = row.conditions.languageSlot === 'all'
        ? ''
        : ` if language_slot == ${Number.parseInt(row.conditions.languageSlot, 10)}`;
      return `        (${rustString(row.sourceBoundaryId)}, ${rustString(row.sourceFace)})${condition} => {
            Some(&${config.constantStem}_RULES[${index}])
        }`;
    }).join('\n');
    return `
#[rustfmt::skip]
pub(crate) fn find_font_rule_layout_name(
    source_boundary_id: &str,
    source_face: &str,
    language_slot: usize,
) -> Option<&'static GeneratedFontRuleProjection> {
    match (source_boundary_id, source_face) {
${arms}
        _ => None,
    }
}`;
  }
  if (config.projectionId === 'rust-layout-metric') {
    const arms = rows.map((row, index) => `        ${rustString(row.sourceFace)} => {
            Some(&${config.constantStem}_RULES[${index}])
        }`).join('\n');
    return `
#[rustfmt::skip]
pub(crate) fn find_font_rule_layout_metric(
    source_face: &str,
) -> Option<&'static GeneratedFontRuleProjection> {
    match source_face {
${arms}
        _ => None,
    }
}`;
  }
  throw new Error(`${config.projectionId}: unsupported Rust projection lookup`);
}

function renderRust(config, metadata, rows) {
  const entries = rows.map(row => [
    '    GeneratedFontRuleProjection {',
    `        rule_id: ${rustString(row.ruleId)},`,
    `        source_boundary_id: ${rustString(row.sourceBoundaryId)},`,
    `        relation_type: ${rustString(row.relationType)},`,
    `        decision_plane: ${rustString(row.decisionPlane)},`,
    `        source_face: ${rustOptionString(row.sourceFace)},`,
    `        target_face_or_policy: ${rustString(row.targetFaceOrPolicy)},`,
    '        conditions: GeneratedFontRuleConditions {',
    `            language_slot: ${rustOptionString(row.conditions.languageSlot)},`,
    `            alt_type: ${rustOptionString(row.conditions.altType)},`,
    `            availability: ${rustOptionString(row.conditions.availability)},`,
    `            profile: ${rustOptionString(row.conditions.profile)},`,
    '        },',
    `        order: ${rustOptionInteger(row.order)},`,
    `        mode: ${rustString(row.mode)},`,
    ...rustMetricEntryLines(row.metricEntryIds),
    '    },',
  ].join('\n')).join('\n');
  return `${GENERATED_SENTINEL}
// Whole-file ownership: regenerate with \`node scripts/font_rule_projection_gen.mjs generate\`.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct GeneratedFontRuleConditions {
    pub(crate) language_slot: Option<&'static str>,
    pub(crate) alt_type: Option<&'static str>,
    pub(crate) availability: Option<&'static str>,
    pub(crate) profile: Option<&'static str>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct GeneratedFontRuleProjection {
    pub(crate) rule_id: &'static str,
    pub(crate) source_boundary_id: &'static str,
    pub(crate) relation_type: &'static str,
    pub(crate) decision_plane: &'static str,
    pub(crate) source_face: Option<&'static str>,
    pub(crate) target_face_or_policy: &'static str,
    pub(crate) conditions: GeneratedFontRuleConditions,
    pub(crate) order: Option<usize>,
    pub(crate) mode: &'static str,
    pub(crate) metric_entry_ids: &'static [&'static str],
}

pub(crate) const ${config.constantStem}_SCHEMA_VERSION: &str =
    crate::schema_registry::FONT_RULE_PROJECTION_SCHEMA_VERSION;
pub(crate) const ${config.constantStem}_INPUT_SHA256: &str =
    ${rustString(metadata.inputSha256)};
pub(crate) const ${config.constantStem}_PROJECTION_SHA256: &str =
    ${rustString(metadata.projectionSha256)};

pub(crate) static ${config.constantStem}_RULES: &[GeneratedFontRuleProjection] = &[
${entries}
];
${renderRustLookup(config, rows)}
`;
}

function renderTypeScript(config, metadata, rows) {
  const metadataJson = JSON.stringify(metadata, null, 2);
  const rowsJson = JSON.stringify(rows, null, 2);
  return `${GENERATED_SENTINEL}
// Whole-file ownership: regenerate with \`node scripts/font_rule_projection_gen.mjs generate\`.

export type GeneratedFontRuleConditions = Readonly<{
  languageSlot?: string | null;
  altType?: string | null;
  availability?: string | null;
  profile?: string | null;
}>;

export type GeneratedFontRuleProjection = Readonly<{
  ruleId: string;
  sourceBoundaryId: string;
  relationType: string;
  decisionPlane: string;
  sourceFace: string | null;
  targetFaceOrPolicy: string;
  conditions: GeneratedFontRuleConditions;
  order: number | null;
  mode: 'direct' | 'legacy-preservation';
  metricEntryIds: readonly string[];
  supply: Readonly<Record<string, unknown>> | null;
}>;

export const ${config.constantStem}_META = Object.freeze(${metadataJson});

export const ${config.constantStem}_RULES: readonly GeneratedFontRuleProjection[] = Object.freeze(${rowsJson});
`;
}

function countByProjection(registry) {
  const counts = Object.fromEntries(OUTPUT_CONFIGS.map(config => [config.projectionId, 0]));
  for (const rule of registry.rules.filter(candidate => candidate.status === 'active')) {
    const projectionId = rule.projections[0].id;
    counts[projectionId] = (counts[projectionId] ?? 0) + 1;
  }
  return Object.fromEntries(Object.entries(counts).sort(([left], [right]) => (
    left < right ? -1 : left > right ? 1 : 0
  )));
}

export function buildProjectionBundle(
  registry = readJson(REGISTRY_PATH),
  root = ROOT,
  generatorSource = fs.readFileSync(GENERATOR_PATH),
) {
  const registryErrors = validateRegistryV2(registry, root);
  if (registryErrors.length > 0) throw new Error(registryErrors.join('\n'));
  const registrySha256 = sha256Text(canonicalJson(registry));
  const outputs = OUTPUT_CONFIGS.map(config => {
    const inputRules = registry.rules
      .filter(rule => (
        rule.status === 'active' && rule.projections[0].id === config.projectionId
      ))
      .sort((left, right) => left.projectionSequence - right.projectionSequence);
    const rows = inputRules.map(rule => projectionRow(rule));
    const inputSha256 = sha256Text(canonicalJson(inputRules));
    const projectionSha256 = sha256Text(canonicalJson(rows));
    const metadata = {
      schemaVersion: '1.0',
      sourceCommit: registry.sourceCommit,
      inputSha256,
      projectionId: config.projectionId,
      projectionSha256,
      ruleCount: rows.length,
    };
    const content = config.language === 'rust'
      ? renderRust(config, metadata, rows)
      : renderTypeScript(config, metadata, rows);
    return {
      projectionId: config.projectionId,
      language: config.language,
      path: config.path,
      ownership: 'generated-whole-file',
      ruleCount: rows.length,
      inputSha256,
      projectionSha256,
      contentSha256: sha256Bytes(content),
      content,
      rows,
    };
  });
  const publicOutputs = outputs.map(({ content: _content, rows: _rows, ...output }) => output);
  const projectionBundle = publicOutputs.map(output => ({
    projectionId: output.projectionId,
    ruleCount: output.ruleCount,
    inputSha256: output.inputSha256,
    projectionSha256: output.projectionSha256,
  }));
  const contentBundle = publicOutputs.map(output => ({
    path: output.path,
    contentSha256: output.contentSha256,
  }));
  const manifest = {
    schemaVersion: '2.0',
    kind: 'font-rule-backend-projection-manifest',
    issue: 5955,
    sourceCommit: registry.sourceCommit,
    schema: pathDigest(MANIFEST_SCHEMA_PATH, root),
    generatedBy: {
      path: relativePath(GENERATOR_PATH, root),
      sha256: sha256Bytes(generatorSource),
    },
    registry: {
      path: relativePath(REGISTRY_PATH, root),
      sha256: registrySha256,
      rulesSha256: registry.rulesSha256,
      activeRuleCount: registry.summary.activeRuleCount,
      retiredRuleCount: registry.summary.retiredRuleCount,
    },
    summary: {
      outputCount: outputs.length,
      activeRuleCount: outputs.reduce((count, output) => count + output.ruleCount, 0),
      retiredRuleCount: registry.summary.retiredRuleCount,
      countsByProjection: countByProjection(registry),
    },
    projectionBundleSha256: sha256Text(canonicalJson(projectionBundle)),
    contentBundleSha256: sha256Text(canonicalJson(contentBundle)),
    outputs: publicOutputs,
  };
  const errors = validateProjectionManifest(manifest, outputs, registry, root, generatorSource);
  if (errors.length > 0) throw new Error(errors.join('\n'));
  return { manifest, outputs };
}

function safeRelativePath(value) {
  return typeof value === 'string'
    && value.length > 0
    && !path.isAbsolute(value)
    && !value.split('/').includes('..')
    && !value.includes('\\');
}

export function validateProjectionManifest(
  manifest,
  outputs,
  registry,
  root = ROOT,
  generatorSource = fs.readFileSync(GENERATOR_PATH),
) {
  const errors = [];
  if (manifest?.schemaVersion !== '2.0'
      || manifest.kind !== 'font-rule-backend-projection-manifest'
      || manifest.issue !== 5955
      || manifest.sourceCommit !== registry.sourceCommit) {
    return ['projection manifest envelope is invalid'];
  }
  const expectedPaths = OUTPUT_CONFIGS.map(config => config.path);
  const actualPaths = manifest.outputs?.map(output => output.path) ?? [];
  if (canonicalJson(actualPaths) !== canonicalJson(expectedPaths)
      || new Set(actualPaths).size !== expectedPaths.length) {
    errors.push('projection output paths must match the five-file allowlist in order');
  }
  if ((manifest.outputs ?? []).some(output => !safeRelativePath(output.path))) {
    errors.push('projection output paths must be safe checkout-relative paths');
  }
  if (manifest.schema?.path !== relativePath(MANIFEST_SCHEMA_PATH, root)
      || manifest.schema?.sha256 !== sha256File(MANIFEST_SCHEMA_PATH)) {
    errors.push('projection manifest schema digest mismatch');
  }
  if (manifest.generatedBy?.path !== relativePath(GENERATOR_PATH, root)
      || manifest.generatedBy?.sha256 !== sha256Bytes(generatorSource)) {
    errors.push('projection generator digest mismatch');
  }
  const registrySha256 = sha256Text(canonicalJson(registry));
  if (manifest.registry?.path !== relativePath(REGISTRY_PATH, root)
      || manifest.registry?.sha256 !== registrySha256
      || manifest.registry?.rulesSha256 !== registry.rulesSha256
      || manifest.registry?.activeRuleCount !== registry.summary.activeRuleCount
      || manifest.registry?.retiredRuleCount !== registry.summary.retiredRuleCount) {
    errors.push('projection registry digest mismatch');
  }
  const counts = countByProjection(registry);
  const activeRuleCount = Object.values(counts).reduce((count, value) => count + value, 0);
  if (manifest.summary?.outputCount !== 5
      || manifest.summary?.activeRuleCount !== activeRuleCount
      || manifest.summary?.activeRuleCount !== registry.summary.activeRuleCount
      || manifest.summary?.retiredRuleCount !== registry.summary.retiredRuleCount
      || canonicalJson(manifest.summary?.countsByProjection) !== canonicalJson(counts)) {
    errors.push('projection manifest population mismatch');
  }
  if (outputs.length !== 5) errors.push('projection bundle must contain five outputs');
  for (const [index, output] of outputs.entries()) {
    const config = OUTPUT_CONFIGS[index];
    const declared = manifest.outputs?.[index];
    if (!declared
        || output.projectionId !== config.projectionId
        || output.language !== config.language
        || output.path !== config.path
        || output.ownership !== 'generated-whole-file'
        || output.ruleCount !== counts[config.projectionId]
        || output.rows.length !== output.ruleCount
        || output.contentSha256 !== sha256Bytes(output.content)
        || canonicalJson(declared) !== canonicalJson({
          projectionId: output.projectionId,
          language: output.language,
          path: output.path,
          ownership: output.ownership,
          ruleCount: output.ruleCount,
          inputSha256: output.inputSha256,
          projectionSha256: output.projectionSha256,
          contentSha256: output.contentSha256,
        })) {
      errors.push(`${config.projectionId}: generated output metadata mismatch`);
    }
    if (!output.content.startsWith(`${GENERATED_SENTINEL}\n`)) {
      errors.push(`${config.projectionId}: whole-file ownership sentinel is missing`);
    }
    if (sha256Text(canonicalJson(output.rows)) !== output.projectionSha256
        || output.rows.some(row => typeof row.ruleId !== 'string')) {
      errors.push(`${config.projectionId}: rule projection hash or ruleId provenance mismatch`);
    }
  }
  const retiredRuleIds = new Set(registry.rules
    .filter(rule => rule.status === 'retired')
    .map(rule => rule.ruleId));
  if (outputs.some(output => output.rows.some(row => retiredRuleIds.has(row.ruleId)))) {
    errors.push('retired rule leaked into a runtime projection');
  }
  const projectionBundle = outputs.map(output => ({
    projectionId: output.projectionId,
    ruleCount: output.ruleCount,
    inputSha256: output.inputSha256,
    projectionSha256: output.projectionSha256,
  }));
  const contentBundle = outputs.map(output => ({
    path: output.path,
    contentSha256: output.contentSha256,
  }));
  if (manifest.projectionBundleSha256 !== sha256Text(canonicalJson(projectionBundle))) {
    errors.push('projection bundle digest mismatch');
  }
  if (manifest.contentBundleSha256 !== sha256Text(canonicalJson(contentBundle))) {
    errors.push('projection content bundle digest mismatch');
  }
  return errors;
}

function generatedDirectoryAllowlist() {
  const map = new Map();
  for (const config of OUTPUT_CONFIGS) {
    const directory = path.posix.dirname(config.path);
    const names = map.get(directory) ?? new Set();
    names.add(path.posix.basename(config.path));
    map.set(directory, names);
  }
  return map;
}

function unexpectedGeneratedFiles(root) {
  const unexpected = [];
  for (const [directory, names] of generatedDirectoryAllowlist()) {
    const absoluteDirectory = path.join(root, directory);
    if (!fs.existsSync(absoluteDirectory)) continue;
    const directoryStat = fs.lstatSync(absoluteDirectory);
    if (!directoryStat.isDirectory() || directoryStat.isSymbolicLink()) {
      unexpected.push(`${directory} (non-directory or symlink)`);
      continue;
    }
    for (const entry of fs.readdirSync(absoluteDirectory, { withFileTypes: true })) {
      if (!entry.isFile() || !names.has(entry.name)) {
        unexpected.push(`${directory}/${entry.name}`);
      }
    }
  }
  return unexpected;
}

export function compareProjectionBundle(bundle, root = ROOT) {
  const errors = [];
  const unexpected = unexpectedGeneratedFiles(root);
  if (unexpected.length > 0) {
    errors.push(`unexpected files in generated projection directories: ${unexpected.join(', ')}`);
  }
  const expectedManifest = canonicalJson(bundle.manifest);
  const manifestTarget = path.join(root, relativePath(MANIFEST_PATH));
  if (!fs.existsSync(manifestTarget)) {
    errors.push('projection manifest is missing');
  } else if (!fs.lstatSync(manifestTarget).isFile()
      || fs.lstatSync(manifestTarget).isSymbolicLink()) {
    errors.push('projection manifest must be a regular non-symlink file');
  } else if (fs.readFileSync(manifestTarget, 'utf8') !== expectedManifest) {
    errors.push('projection manifest is stale or manually edited');
  }
  for (const output of bundle.outputs) {
    const target = path.join(root, output.path);
    if (!fs.existsSync(target)) {
      errors.push(`${output.path}: generated projection is missing`);
    } else if (!fs.lstatSync(target).isFile() || fs.lstatSync(target).isSymbolicLink()) {
      errors.push(`${output.path}: generated projection must be a regular non-symlink file`);
    } else if (fs.readFileSync(target, 'utf8') !== output.content) {
      errors.push(`${output.path}: generated projection is stale or manually edited`);
    }
  }
  return errors;
}

function withinRoot(realRoot, candidate) {
  return candidate === realRoot || candidate.startsWith(`${realRoot}${path.sep}`);
}

function validateOwnedTarget(target, kind) {
  if (!fs.existsSync(target)) return;
  const stat = fs.lstatSync(target);
  if (!stat.isFile() || stat.isSymbolicLink()) {
    throw new Error(`generated output target must be a regular non-symlink file: ${target}`);
  }
  const content = fs.readFileSync(target, 'utf8');
  if (kind === 'manifest') {
    let parsed;
    try {
      parsed = JSON.parse(content);
    } catch {
      throw new Error(`existing projection manifest is not owned by this generator: ${target}`);
    }
    const legacyOwner = parsed.kind === 'font-rule-backend-projection-manifest'
      && parsed.schemaVersion === '1.0'
      && parsed.issue === 4966;
    const currentOwner = parsed.kind === 'font-rule-backend-projection-manifest'
      && parsed.schemaVersion === '2.0'
      && parsed.issue === 5955;
    if (!(legacyOwner || currentOwner)) {
      throw new Error(`existing projection manifest is not owned by this generator: ${target}`);
    }
  } else if (!(content.startsWith(`${GENERATED_SENTINEL}\n`)
      || content.startsWith(`${LEGACY_GENERATED_SENTINEL}\n`))) {
    throw new Error(`refusing to overwrite a file without the whole-file ownership sentinel: ${target}`);
  }
}

function uniqueSibling(target, suffix) {
  const parent = path.dirname(target);
  const name = path.basename(target);
  for (let attempt = 0; attempt < 100; attempt += 1) {
    stagedSequence += 1;
    const candidate = path.join(
      parent,
      `.${name}.${process.pid}.${stagedSequence}.${suffix}`,
    );
    if (!fs.existsSync(candidate)) return candidate;
  }
  throw new Error(`cannot reserve a sibling staging path for ${target}`);
}

export function writeProjectionBundle(bundle, root = ROOT, hooks = {}) {
  const unexpected = unexpectedGeneratedFiles(root);
  if (unexpected.length > 0) {
    throw new Error(`refusing to overwrite a non-allowlisted generated path: ${unexpected.join(', ')}`);
  }
  const realRoot = fs.realpathSync(root);
  const entries = [
    ...bundle.outputs.map(output => ({
      target: path.join(root, output.path),
      content: output.content,
      kind: 'source',
    })),
    {
      target: path.join(root, relativePath(MANIFEST_PATH)),
      content: canonicalJson(bundle.manifest),
      kind: 'manifest',
    },
  ];
  for (const entry of entries) {
    fs.mkdirSync(path.dirname(entry.target), { recursive: true });
    const realParent = fs.realpathSync(path.dirname(entry.target));
    if (!withinRoot(realRoot, realParent)) {
      throw new Error(`generated output parent escapes the checkout: ${entry.target}`);
    }
    validateOwnedTarget(entry.target, entry.kind);
  }

  const staged = [];
  const backups = [];
  const committed = [];
  let commitComplete = false;
  try {
    for (const entry of entries) {
      const stagedPath = uniqueSibling(entry.target, 'rhwp-stage');
      const descriptor = fs.openSync(stagedPath, 'wx');
      try {
        fs.writeFileSync(descriptor, entry.content, 'utf8');
        fs.fsyncSync(descriptor);
      } finally {
        fs.closeSync(descriptor);
      }
      staged.push({ ...entry, stagedPath });
    }
    for (const entry of staged) {
      if (!fs.existsSync(entry.target)) continue;
      const backupPath = uniqueSibling(entry.target, 'rhwp-backup');
      fs.renameSync(entry.target, backupPath);
      backups.push({ target: entry.target, backupPath });
    }
    for (const [index, entry] of staged.entries()) {
      hooks.beforeCommit?.(index, entry);
      fs.renameSync(entry.stagedPath, entry.target);
      committed.push(entry.target);
    }
    commitComplete = true;
  } catch (error) {
    for (const target of committed.reverse()) fs.rmSync(target, { force: true });
    for (const backup of backups.reverse()) {
      if (fs.existsSync(backup.backupPath)) fs.renameSync(backup.backupPath, backup.target);
    }
    throw error;
  } finally {
    for (const entry of staged) fs.rmSync(entry.stagedPath, { force: true });
    if (!commitComplete) {
      for (const backup of backups) fs.rmSync(backup.backupPath, { force: true });
    }
  }
  const cleanupErrors = [];
  for (const backup of backups) {
    try {
      fs.rmSync(backup.backupPath, { force: true });
    } catch (error) {
      cleanupErrors.push(`${backup.backupPath}: ${error.message}`);
    }
  }
  if (cleanupErrors.length > 0) {
    throw new Error(`generated outputs committed but backup cleanup failed:\n${cleanupErrors.join('\n')}`);
  }
}

const invokedPath = process.argv[1] ? path.resolve(process.argv[1]) : '';
if (invokedPath === fileURLToPath(import.meta.url)) {
  try {
    const command = process.argv[2];
    if (process.argv.length > 3) {
      throw new Error('font rule projection generator uses fixed checkout-root output paths');
    }
    const bundle = buildProjectionBundle();
    if (command === 'generate') {
      writeProjectionBundle(bundle);
      process.stdout.write(
        `font rule projections: generated ${bundle.outputs.length} outputs, `
          + `${bundle.manifest.summary.activeRuleCount} active rules\n`,
      );
    } else if (command === 'check') {
      const errors = compareProjectionBundle(bundle);
      if (errors.length > 0) throw new Error(errors.join('\n'));
      process.stdout.write('font rule projections: ok\n');
    } else {
      throw new Error('usage: font_rule_projection_gen.mjs <generate|check>');
    }
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  }
}
