// @generated by scripts/font_rule_projection_gen.mjs from assets/font-rules/font_rule_registry_v2.json; DO NOT EDIT.
// Whole-file ownership: regenerate with `node scripts/font_rule_projection_gen.mjs generate`.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct GeneratedFontRuleConditions {
    pub(crate) language_slot: Option<&'static str>,
    pub(crate) alt_type: Option<&'static str>,
    pub(crate) availability: Option<&'static str>,
    pub(crate) profile: Option<&'static str>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct GeneratedFontRuleProjection {
    pub(crate) rule_id: &'static str,
    pub(crate) source_boundary_id: &'static str,
    pub(crate) relation_type: &'static str,
    pub(crate) decision_plane: &'static str,
    pub(crate) source_face: Option<&'static str>,
    pub(crate) target_face_or_policy: &'static str,
    pub(crate) conditions: GeneratedFontRuleConditions,
    pub(crate) order: Option<usize>,
    pub(crate) mode: &'static str,
    pub(crate) metric_entry_ids: &'static [&'static str],
}

pub(crate) const FONT_RULE_LAYOUT_METRIC_SCHEMA_VERSION: &str =
    crate::schema_registry::FONT_RULE_PROJECTION_SCHEMA_VERSION;
pub(crate) const FONT_RULE_LAYOUT_METRIC_INPUT_SHA256: &str =
    "355fde530a2f7d40b539ab534c52251bf6697a5632136bee416842a19f2230dd";
pub(crate) const FONT_RULE_LAYOUT_METRIC_PROJECTION_SHA256: &str =
    "c4659fc40246c5d4ad903578a61807c646681638cb4c8f9b7c802fb3f0c37cc2";

pub(crate) static FONT_RULE_LAYOUT_METRIC_RULES: &[GeneratedFontRuleProjection] = &[
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.cf9164c17319ba49ddd8",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("함초롬돋움"),
        target_face_or_policy: "HCR Dotum",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &[
            "font-metric.afe9fdb40f52526f9c46",
            "font-metric.49f371732df068ec9465",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.50e8b4fe44e2633d21f9",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("한컴돋움"),
        target_face_or_policy: "Haansoft Dotum",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.88559f44ea794ed00c09"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.1378b1b9d9506f86a014",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("돋움"),
        target_face_or_policy: "Dotum",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.88f8cb93ba7864aaa9c4"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.1de1fcb9b17d66d599b5",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("함초롬바탕"),
        target_face_or_policy: "HCR Batang",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &[
            "font-metric.bd0108b707fa10f340df",
            "font-metric.5f8e3a0bc02ff32d61e1",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.7a2702136cc80f952133",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("한컴바탕"),
        target_face_or_policy: "Haansoft Batang",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.6e7f62f6460360f3b0d7"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.699fcfcdb4b25070dc37",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("바탕"),
        target_face_or_policy: "Batang",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.edec2573883b7b4dc023"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.e69131207a16d7535d80",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("맑은 고딕"),
        target_face_or_policy: "Malgun Gothic",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &[
            "font-metric.cb5db76c0649913e4438",
            "font-metric.1beeab194e16e4a6107d",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.5ff808f5409744c0a1b0",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("나눔고딕"),
        target_face_or_policy: "NanumGothic",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &[
            "font-metric.42a6775df0ad677916ff",
            "font-metric.9aa4e5419b3d55980782",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.1464fe2bf651f25c3060",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("나눔명조"),
        target_face_or_policy: "NanumMyeongjo",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &[
            "font-metric.d39c74829843c96f455a",
            "font-metric.061fd77a68a8804b7f10",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.980ac0a95716c7a62c4a",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("바탕체"),
        target_face_or_policy: "BatangChe",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.2fa7c36153b6fc8e1f5a"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.34c100f7862575a46540",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("굴림"),
        target_face_or_policy: "Gulim",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.7cbe0f6d2c114cb01570"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.8cdee6ea2e6a2099d9dc",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("궁서"),
        target_face_or_policy: "Gungsuh",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.22470a44e448b3b44ed8"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.b2b4b3bf73bbdcae40b5",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("굴림체"),
        target_face_or_policy: "GulimChe",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.99899fa72a2871ba7558"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.9bdad5ff6a5c5fe55bf7",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("돋움체"),
        target_face_or_policy: "DotumChe",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.00f1682c2a093d82eaa8"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.7e74e1181bd29a93343b",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("궁서체"),
        target_face_or_policy: "GungsuhChe",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.9f646214e8f5da6db1eb"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.ee88ac9b7256e14b1034",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("D2Coding"),
        target_face_or_policy: "D2Coding",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.5dc89d5c18cec1573c2f"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.a8941ceca1bf044e21bd",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("D2 Coding"),
        target_face_or_policy: "D2Coding",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.5dc89d5c18cec1573c2f"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.c90981a0f93928779824",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("고운바탕"),
        target_face_or_policy: "Gowun Batang",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.3a8f525c04313e627c6a"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.0be3736c8eb2a5dd33fb",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("Gowun Batang"),
        target_face_or_policy: "Gowun Batang",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.3a8f525c04313e627c6a"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.a2509235152a1ac5c875",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("고운돋움"),
        target_face_or_policy: "Gowun Dodum",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.6b4bbb3c557d1ac504cc"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.b4f149e0beb1732c1da7",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("Gowun Dodum"),
        target_face_or_policy: "Gowun Dodum",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.6b4bbb3c557d1ac504cc"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.851b868ea4a0e030660b",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("Pretendard"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.f21ebe3ed64dcd2ad18e",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("프리텐다드"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.bedc15cfc3048b3367e7",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY중고딕"),
        target_face_or_policy: "HYGothic-Medium",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.f7187a5d277323eb9041"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.04b2e35585c329e276eb",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY견고딕"),
        target_face_or_policy: "HYGothic-Extra",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.786819006e45655f5742"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.1f9388631aac491d3380",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY헤드라인M"),
        target_face_or_policy: "HYHeadLine-Medium",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.ed80c3de6f2b1cde0ed6"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.f1450144ca329b7be879",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY견명조"),
        target_face_or_policy: "HYMyeongJo-Extra",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.cdeb35487f5d8578668c"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.1444c98cb745d946782a",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY신명조"),
        target_face_or_policy: "HYSinMyeongJo-Medium",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.2b7a4214d610ebc0d2e9"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.b5c0f0d1efa629d562f2",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY그래픽"),
        target_face_or_policy: "HYGraphic-Medium",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.f3998378839f7b435477"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.e648f19ca68dd7c3cebe",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY궁서"),
        target_face_or_policy: "HYGungSo-Bold",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.0c7f1e3e27999d6d5ba7"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.e3b10e6770cafa77ff71",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("한양신명조"),
        target_face_or_policy: "HanyangSinMyeongJo",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.d65f82c2328027f962d5"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.f87d4d432ef2820f9c8f",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("한양중고딕"),
        target_face_or_policy: "HanyangJungGothic",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.5e27ba1723bb0bda377b"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.d51ea95a4f72143e4b51",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("한양견명조"),
        target_face_or_policy: "HanyangKyunMyeongJo",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.207f07f70b3cc8d04bc9"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.c28b0b6b6dfd7f3adf86",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("한양견고딕"),
        target_face_or_policy: "HanyangKyunGothic",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.1351a4e801d19c03c572"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.4f65d46263459fd6e3eb",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("휴먼명조"),
        target_face_or_policy: "HumanMyeongJo",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.9a8bbb709cc97fb70635"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.a1d58eacfc8e7abdaf9b",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("신명조"),
        target_face_or_policy: "HanyangSinMyeongJo",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.d65f82c2328027f962d5"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.d1edee136a66e4703a19",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY수평선B"),
        target_face_or_policy: "HYsupB",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.ac47ab5ff3a0f4c394da"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.7867c1d6f35f35f56fee",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY수평선M"),
        target_face_or_policy: "HYsupM",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.f86349e2ab11b4b5e02f"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.2dc7a889b1fdf42b4e88",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY울릉도B"),
        target_face_or_policy: "HYwulB",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.6d5a96f9a1978b15c8a2"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.c38460dc5362fdf16080",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY울릉도M"),
        target_face_or_policy: "HYwulM",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.7529fe3db1f263152b07"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.48163357a589b288e4f3",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY태백B"),
        target_face_or_policy: "HYtbrB",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.4fe8206ed44b025517e4"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.e5beb2bc96916f59b69c",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY동녘B"),
        target_face_or_policy: "HYdnkB",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.b781e0cd5343ec31f8a9"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.9bbf1f249a62f66d4ebf",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "unknown",
        decision_plane: "layout-metric",
        source_face: Some("HY동녘M"),
        target_face_or_policy: "HYdnkM",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "legacy-preservation",
        metric_entry_ids: &["font-metric.2fbf185f465d86525a0c"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.0b74264b87ed459ef5db",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("HY각헤드라인M"),
        target_face_or_policy: "HYHeadLine-Medium",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &["font-metric.ed80c3de6f2b1cde0ed6"],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.93f116972afe7a9e11eb",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("본한글"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.d96477e4644e99cd7691",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("본한글vf"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.dab0a6bfa6a6808c7e85",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("본한글 Medium"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.886d1096849aa4cda4f7",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("본한글M"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.400afb74baa546fb4d4e",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("본고딕"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.0903e43e3f6a5ae0a529",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("본고딕vf"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.367693a49a433a73e7c6",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("Source Han Sans"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.e8f8e8dcdae67262e1f7",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("Source Han Sans K"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.77b342ddf3e5f56a93b2",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("Source Han Sans KR"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.ee40ac70aabb4cc9e6b7",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("SourceHanSans"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.8c43678832f0128a5dbd",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("SourceHanSansKR"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.e68b648ce9e0bf03e8af",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("SourceHanSansK"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.3fe706a98ce06e43fcdc",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("Noto Sans CJK KR"),
        target_face_or_policy: "Pretendard",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.bd6f881e3233d4fb5ab7",
            "font-metric.924498e4d129eafd11f2",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.d00a815cbc70ff4e6431",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("본명조"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.5e3db6b9c199a391c020",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("본명조vf"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.101b5492e9ee5f51c63d",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("본명조M"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.62ca200fda3d5dcdd29e",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("Source Han Serif"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.c0042ffc793ee3e4eb89",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("Source Han Serif K"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.ec2620f215badc37ea34",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("Source Han Serif KR"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.bb4f965303acb84d2aed",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("SourceHanSerif"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.a4a9d604841fce9ca663",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("SourceHanSerifKR"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.44f727b9ee703362b848",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("SourceHanSerifK"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
    GeneratedFontRuleProjection {
        rule_id: "rule.rust-metric.4cbb2d8c4a64bf90fdc8",
        source_boundary_id: "rust-metric.metric-alias",
        relation_type: "metric-surrogate",
        decision_plane: "layout-metric",
        source_face: Some("Noto Serif CJK KR"),
        target_face_or_policy: "Noto Serif KR",
        conditions: GeneratedFontRuleConditions {
            language_slot: None,
            alt_type: None,
            availability: None,
            profile: None,
        },
        order: None,
        mode: "direct",
        metric_entry_ids: &[
            "font-metric.669b60a1985a2b784ed3",
            "font-metric.6cef32736604b65b441e",
        ],
    },
];

#[rustfmt::skip]
pub(crate) fn find_font_rule_layout_metric(
    source_face: &str,
) -> Option<&'static GeneratedFontRuleProjection> {
    match source_face {
        "함초롬돋움" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[0])
        }
        "한컴돋움" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[1])
        }
        "돋움" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[2])
        }
        "함초롬바탕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[3])
        }
        "한컴바탕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[4])
        }
        "바탕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[5])
        }
        "맑은 고딕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[6])
        }
        "나눔고딕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[7])
        }
        "나눔명조" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[8])
        }
        "바탕체" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[9])
        }
        "굴림" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[10])
        }
        "궁서" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[11])
        }
        "굴림체" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[12])
        }
        "돋움체" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[13])
        }
        "궁서체" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[14])
        }
        "D2Coding" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[15])
        }
        "D2 Coding" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[16])
        }
        "고운바탕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[17])
        }
        "Gowun Batang" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[18])
        }
        "고운돋움" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[19])
        }
        "Gowun Dodum" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[20])
        }
        "Pretendard" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[21])
        }
        "프리텐다드" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[22])
        }
        "HY중고딕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[23])
        }
        "HY견고딕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[24])
        }
        "HY헤드라인M" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[25])
        }
        "HY견명조" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[26])
        }
        "HY신명조" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[27])
        }
        "HY그래픽" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[28])
        }
        "HY궁서" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[29])
        }
        "한양신명조" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[30])
        }
        "한양중고딕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[31])
        }
        "한양견명조" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[32])
        }
        "한양견고딕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[33])
        }
        "휴먼명조" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[34])
        }
        "신명조" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[35])
        }
        "HY수평선B" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[36])
        }
        "HY수평선M" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[37])
        }
        "HY울릉도B" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[38])
        }
        "HY울릉도M" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[39])
        }
        "HY태백B" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[40])
        }
        "HY동녘B" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[41])
        }
        "HY동녘M" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[42])
        }
        "HY각헤드라인M" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[43])
        }
        "본한글" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[44])
        }
        "본한글vf" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[45])
        }
        "본한글 Medium" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[46])
        }
        "본한글M" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[47])
        }
        "본고딕" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[48])
        }
        "본고딕vf" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[49])
        }
        "Source Han Sans" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[50])
        }
        "Source Han Sans K" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[51])
        }
        "Source Han Sans KR" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[52])
        }
        "SourceHanSans" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[53])
        }
        "SourceHanSansKR" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[54])
        }
        "SourceHanSansK" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[55])
        }
        "Noto Sans CJK KR" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[56])
        }
        "본명조" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[57])
        }
        "본명조vf" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[58])
        }
        "본명조M" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[59])
        }
        "Source Han Serif" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[60])
        }
        "Source Han Serif K" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[61])
        }
        "Source Han Serif KR" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[62])
        }
        "SourceHanSerif" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[63])
        }
        "SourceHanSerifKR" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[64])
        }
        "SourceHanSerifK" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[65])
        }
        "Noto Serif CJK KR" => {
            Some(&FONT_RULE_LAYOUT_METRIC_RULES[66])
        }
        _ => None,
    }
}
